In [ ]:
import pandas as pd

In [ ]:
df_recom = pd.read_csv("/content/drive/MyDrive/data_movie/data_movie/ratings.csv")

In [ ]:
df_movies = pd.read_csv("/content/drive/MyDrive/data_movie/data_movie/movies.csv")

In [ ]:
df_movies

,movieId,genres,movie_name,year
0,1,"['Adventure', 'Animation', 'Children', 'Comedy...",Toy Story,1995.0
1,2,"['Adventure', 'Children', 'Fantasy']",Jumanji,1995.0
2,3,"['Comedy', 'Romance']",Grumpier Old Men,1995.0
3,4,"['Comedy', 'Drama', 'Romance']",Waiting to Exhale,1995.0
4,5,['Comedy'],Father of the Bride Part II,1995.0
...,...,...,...,...
27273,131254,['Comedy'],Kein Bund für's Leben,2007.0
27274,131256,['Comedy'],"Feuer, Eis & Dosenbier",2002.0
27275,131258,['Adventure'],The Pirates,2014.0
27276,131260,['(no genres listed)'],Rentun Ruusu,2001.0
27277,131262,"['Adventure', 'Fantasy', 'Horror']",Innocence,2014.0

In [ ]:
df_recom.head()

   userId  movieId  rating
0       1        2     3.5
1       1       29     3.5
2       1       32     3.5
3       1       47     3.5
4       1       50     3.5

In [ ]:
df_recom['interaction'] = df_recom['rating'].apply(
    lambda x: 1 if x >= 3.5 else 0
)

In [ ]:
df_recom.head()

   userId  movieId  rating  interaction
0       1        2     3.5            1
1       1       29     3.5            1
2       1       32     3.5            1
3       1       47     3.5            1
4       1       50     3.5            1

In [ ]:
df_movies.head()

,movieId,genres,movie_name,year
0,1,"['Adventure', 'Animation', 'Children', 'Comedy...",Toy Story,1995.0
1,2,"['Adventure', 'Children', 'Fantasy']",Jumanji,1995.0
2,3,"['Comedy', 'Romance']",Grumpier Old Men,1995.0
3,4,"['Comedy', 'Drama', 'Romance']",Waiting to Exhale,1995.0
4,5,['Comedy'],Father of the Bride Part II,1995.0

In [ ]:
df_recom["userId"].nunique()

138493

In [ ]:
df_recom["movieId"].nunique()

26744

In [ ]:
#### using collaborative filtering based on movie ratings

In [ ]:

df_user_bias = pd.DataFrame({"Rating": df_recom.groupby("userId")["rating"].mean(), "Count": df_recom.groupby("userId")["rating"].count()})

In [ ]:

df_user_bias.sort_values(by=["Count", "Rating"], ascending=False)

          Rating  Count
userId
118205  3.279069   9254
8405    3.208317   7515
82418   3.516915   5646
121535  2.793116   5520
125794  3.762976   5491
...          ...    ...
74084   0.500000     20
74276   0.500000     20
103630  0.500000     20
106618  0.500000     20
117730  0.500000     20

[138493 rows x 2 columns]

In [ ]:

df_user_bias.reset_index(inplace=True)

In [ ]:
df_user_bias = df_user_bias[df_user_bias['Count']>50]

In [ ]:
df_user_bias

        userId    Rating  Count
0            1  3.742857    175
1            2  4.000000     61
2            3  4.122995    187
4            5  4.272727     66
6            7  3.289855    276
...        ...       ...    ...
138485  138486  3.800518    193
138486  138487  4.225806     62
138489  138490  3.556291    151
138491  138492  4.097561     82
138492  138493  4.172922    373

[84056 rows x 3 columns]

In [ ]:

df_product_ratings = pd.DataFrame({"rating": df_recom.groupby("movieId")["rating"].mean(), "Count": df_recom.groupby("movieId")["rating"].count()})

In [ ]:
df_product_ratings.sort_values(by=["Count", "rating"], ascending=False)

           rating  Count
movieId
296      4.174231  67310
356      4.029000  66172
318      4.446990  63366
593      4.177057  63299
480      3.664741  59715
...           ...    ...
130672   0.500000      1
130682   0.500000      1
130900   0.500000      1
131062   0.500000      1
131152   0.500000      1

[26744 rows x 2 columns]

In [ ]:

df_product_ratings = df_product_ratings[df_product_ratings['Count']>5]

In [ ]:
df_product_ratings

           rating  Count
movieId
1        3.921240  49695
2        3.211977  22243
3        3.151040  12735
4        2.861393   2756
5        3.064592  12161
...           ...    ...
129937   2.666667     12
130073   3.404762     21
130075   2.500000     17
130490   3.240000     25
130496   2.714286      7

[17519 rows x 2 columns]

In [ ]:
df_product_ratings.reset_index(inplace=True)

In [ ]:


train_data = df_recom[df_recom['userId'].isin(df_user_bias['userId'])]
train_data = df_recom[df_recom['movieId'].isin(df_product_ratings['movieId'])]

In [ ]:
train_data.head()

   userId  movieId  rating  interaction
0       1        2     3.5            1
1       1       29     3.5            1
2       1       32     3.5            1
3       1       47     3.5            1
4       1       50     3.5            1

In [ ]:
len(train_data["movieId"].unique())

17519

In [ ]:
df_movies_filtered =df_movies[df_movies['movieId'].isin(df_product_ratings['movieId'])]

In [ ]:
df_movies_filtered.head()

,movieId,genres,movie_name,year
0,1,"['Adventure', 'Animation', 'Children', 'Comedy...",Toy Story,1995.0
1,2,"['Adventure', 'Children', 'Fantasy']",Jumanji,1995.0
2,3,"['Comedy', 'Romance']",Grumpier Old Men,1995.0
3,4,"['Comedy', 'Drama', 'Romance']",Waiting to Exhale,1995.0
4,5,['Comedy'],Father of the Bride Part II,1995.0

In [ ]:
mapper_id_to_movie= dict(zip(df_movies_filtered["movieId"], df_movies_filtered["movie_name"]))

In [ ]:
len(mapper_id_to_movie)

17519

In [ ]:
import json

with open("/content/drive/MyDrive/data_movie/data_movie/filtering/movie_mapper_orient.json", "w") as f:
  json.dump(mapper_id_to_movie, f)

In [ ]:

train_data.head()

   userId  movieId  rating  interaction
0       1        2     3.5            1
1       1       29     3.5            1
2       1       32     3.5            1
3       1       47     3.5            1
4       1       50     3.5            1

In [ ]:
train_data.drop("rating", axis=1, inplace=True)

/tmp/ipykernel_55637/2647054931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.drop("rating", axis=1, inplace=True)

In [ ]:
train_data.head()

   userId  movieId  interaction
0       1        2            1
1       1       29            1
2       1       32            1
3       1       47            1
4       1       50            1

In [ ]:
final_data = train_data[train_data['interaction']==1]

In [ ]:
len(final_data["movieId"].unique())

17405

In [ ]:
df_movies_filtered =df_movies[df_movies['movieId'].isin(final_data["movieId"].unique())]

In [ ]:
mapper_id_to_movie= dict(zip(df_movies_filtered["movieId"], df_movies_filtered["movie_name"]))

In [ ]:
import json

with open("/content/drive/MyDrive/data_movie/data_movie/filtering/movie_mapper_orient.json", "w") as f:
  json.dump(mapper_id_to_movie, f)

In [ ]:


user_item_interaction = final_data.pivot_table(index='userId', columns="movieId", values='interaction')

/tmp/ipykernel_55637/3023452390.py:1: PerformanceWarning: The following operation may generate 2408190610 cells in the resulting pandas object.
  user_item_interaction = final_data.pivot_table(index='userId', columns="movieId", values='interaction')

In [ ]:

user_item_interaction.fillna(0, inplace = True)

In [ ]:
X = user_item_interaction
X.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,129354,129370,129428,129514,129707,129937,130073,130075,130490,130496
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
movie_ids = list(X.index)

In [ ]:

from sklearn.decomposition import TruncatedSVD


SVD = TruncatedSVD(n_components=30)
decomposed_matrix = SVD.fit_transform(X)
decomposed_matrix.shape

(138362, 30)

In [ ]:
decomposed_matrix

array([[ 5.24911254,  0.19282181, -0.55400016, ..., -0.32925485,
        -0.76058936, -0.96095382],
       [ 1.36574249, -0.27436682,  0.6165739 , ...,  0.24443616,
        -0.03652649, -0.02819057],
       [ 4.89427514, -2.15991711,  0.37623999, ...,  0.59666204,
         0.10818136,  0.05866675],
       ...,
       [ 0.13907407, -0.01247223, -0.10925021, ...,  0.019117  ,
         0.0227929 ,  0.08229147],
       [ 2.63997507, -0.40271428, -1.06778686, ...,  0.40033907,
        -0.00837877,  0.08808018],
       [ 7.40479223,  2.73094371,  0.0780335 , ..., -0.96303388,
        -0.01798793,  0.13206272]])

In [ ]:
from sklearn.neighbors import NearestNeighbors

neighbor_finder = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=10, n_jobs=-1)

In [ ]:
neighbor_finder.fit(decomposed_matrix)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=10)

In [ ]:
import pickle as pkl

In [ ]:
import os

os.makedirs("/content/drive/MyDrive/data_movie/data_movie/filtering", exist_ok=True)

In [ ]:
### storing_item_on_item

In [ ]:
import pickle as pkl

In [ ]:
with open("/content/drive/MyDrive/data_movie/data_movie/filtering/neighbor_finder_movie.pkl", "wb") as f:
  pkl.dump(neighbor_finder, f)

In [ ]:
movie_id =3
user_ids = list(X.index)
movie_index = user_ids.index(movie_id)

In [ ]:
similar_movies = neighbor_finder.kneighbors([decomposed_matrix[movie_index]], return_distance=False)

In [ ]:
similar_movies

array([[  2, 707,   4, 133, 788, 748, 630, 648, 372, 751]])

In [ ]:
### Inference

In [ ]:
mapper_id_to_movie= dict(zip(df_movies["movieId"], df_movies["movie_name"]))

In [ ]:
import numpy as np

np.save("/content/drive/MyDrive/data_movie/data_movie/filtering/interaction_matrix.npy", decomposed_matrix)

In [ ]:
with open("/content/drive/MyDrive/data_movie/data_movie/filtering/movie_ids.pkl", "wb") as f:
  pkl.dump(movie_ids, f)

In [ ]:
mapper_id_to_movie

{1: 'Toy Story',
 2: 'Jumanji',
 3: 'Grumpier Old Men',
 4: 'Waiting to Exhale',
 5: 'Father of the Bride Part II',
 6: 'Heat',
 7: 'Sabrina',
 8: 'Tom and Huck',
 9: 'Sudden Death',
 10: 'GoldenEye',
 11: 'American President, The',
 12: 'Dracula: Dead and Loving It',
 13: 'Balto',
 14: 'Nixon',
 15: 'Cutthroat Island',
 16: 'Casino',
 17: 'Sense and Sensibility',
 18: 'Four Rooms',
 19: 'Ace Ventura: When Nature Calls',
 20: 'Money Train',
 21: 'Get Shorty',
 22: 'Copycat',
 23: 'Assassins',
 24: 'Powder',
 25: 'Leaving Las Vegas',
 26: 'Othello',
 27: 'Now and Then',
 28: 'Persuasion',
 29: 'City of Lost Children, The (Cité des enfants perdus, La)',
 30: 'Shanghai Triad (Yao a yao yao dao waipo qiao)',
 31: 'Dangerous Minds',
 32: 'Twelve Monkeys (a.k.a. 12 Monkeys)',
 33: 'Wings of Courage',
 34: 'Babe',
 35: 'Carrington',
 36: 'Dead Man Walking',
 37: 'Across the Sea of Time',
 38: 'It Takes Two',
 39: 'Clueless',
 40: 'Cry, the Beloved Country',
 41: 'Richard III',
 42: 'Dead Presidents',
 43: 'Restoration',
 44: 'Mortal Kombat',
 45: 'To Die For',
 46: 'How to Make an American Quilt',
 47: 'Seven (a.k.a. Se7en)',
 48: 'Pocahontas',
 49: 'When Night Is Falling',
 50: 'Usual Suspects, The',
 51: 'Guardian Angel',
 52: 'Mighty Aphrodite',
 53: 'Lamerica',
 54: 'Big Green, The',
 55: 'Georgia',
 56: 'Kids of the Round Table',
 57: 'Home for the Holidays',
 58: 'Postman, The (Postino, Il)',
 59: 'Confessional, The (Confessionnal, Le)',
 60: 'Indian in the Cupboard, The',
 61: 'Eye for an Eye',
 62: "Mr. Holland's Opus",
 63: "Don't Be a Menace to South Central While Drinking Your Juice in the Hood",
 64: 'Two if by Sea',
 65: 'Bio-Dome',
 66: 'Lawnmower Man 2: Beyond Cyberspace',
 67: 'Two Bits',
 68: 'French Twist (Gazon maudit)',
 69: 'Friday',
 70: 'From Dusk Till Dawn',
 71: 'Fair Game',
 72: 'Kicking and Screaming',
 73: 'Misérables, Les',
 74: 'Bed of Roses',
 75: 'Big Bully',
 76: 'Screamers',
 77: 'Nico Icon',
 78: 'Crossing Guard, The',
 79: 'Juror, The',
 80: 'White Balloon, The (Badkonake sefid)',
 81: "Things to Do in Denver When You're Dead",
 82: "Antonia's Line (Antonia)",
 83: 'Once Upon a Time... When We Were Colored',
 84: 'Last Summer in the Hamptons',
 85: 'Angels and Insects',
 86: 'White Squall',
 87: 'Dunston Checks In',
 88: 'Black Sheep',
 89: 'Nick of Time',
 90: 'Journey of August King, The',
 92: 'Mary Reilly',
 93: 'Vampire in Brooklyn',
 94: 'Beautiful Girls',
 95: 'Broken Arrow',
 96: 'In the Bleak Midwinter',
 97: 'Hate (Haine, La)',
 98: 'Shopping',
 99: 'Heidi Fleiss: Hollywood Madam',
 100: 'City Hall',
 101: 'Bottle Rocket',
 102: 'Mr. Wrong',
 103: 'Unforgettable',
 104: 'Happy Gilmore',
 105: 'Bridges of Madison County, The',
 106: 'Nobody Loves Me (Keiner liebt mich)',
 107: 'Muppet Treasure Island',
 108: 'Catwalk',
 109: 'Headless Body in Topless Bar',
 110: 'Braveheart',
 111: 'Taxi Driver',
 112: 'Rumble in the Bronx (Hont faan kui)',
 113: 'Before and After',
 114: "Margaret's Museum",
 115: 'Happiness Is in the Field (Bonheur est dans le pré, Le)',
 116: 'Anne Frank Remembered',
 117: "Young Poisoner's Handbook, The",
 118: 'If Lucy Fell',
 119: 'Steal Big, Steal Little',
 120: 'Race the Sun',
 121: 'Boys of St. Vincent, The',
 122: 'Boomerang',
 123: 'Chungking Express (Chung Hing sam lam)',
 124: "Star Maker, The (Uomo delle stelle, L')",
 125: 'Flirting With Disaster',
 126: 'NeverEnding Story III, The',
 127: 'Silences of the Palace, The (Saimt el Qusur)',
 128: "Jupiter's Wife",
 129: 'Pie in the Sky',
 130: 'Angela',
 131: 'Frankie Starlight',
 132: 'Jade',
 133: 'Nueba Yol',
 134: 'Sonic Outlaws',
 135: 'Down Periscope',
 136: 'From the Journals of Jean Seberg',
 137: 'Man of the Year',
 138: 'Neon Bible, The',
 139: 'Target',
 140: 'Up Close and Personal',
 141: 'Birdcage, The',
 142: 'Shadows (Cienie)',
 143: 'Gospa',
 144: 'Brothers McMullen, The',
 145: 'Bad Boys',
 146: 'Amazing Panda Adventure, The',
 147: 'Basketball Diaries, The',
 148: 'Awfully Big Adventure, An',
 149: 'Amateur',
 150: 'Apollo 13',
 151: 'Rob Roy',
 152: 'Addiction, The',
 153: 'Batman Forever',
 154: 'Beauty of the Day (Belle de jour)',
 155: 'Beyond Rangoon',
 156: 'Blue in the Face',
 157: 'Canadian Bacon',
 158: 'Casper',
 159: 'Clockers',
 160: 'Congo',
 161: 'Crimson Tide',
 162: 'Crumb',
 163: 'Desperado',
 164: 'Devil in a Blue Dress',
 165: 'Die Hard: With a Vengeance',
 166: 'Doom Generation, The',
 167: 'Feast of July',
 168: 'First Knight',
 169: 'Free Willy 2: The Adventure Home',
 170: 'Hackers',
 171: 'Jeffrey',
 172: 'Johnny Mnemonic',
 173: 'Judge Dredd',
 174: 'Jury Duty',
 175: 'Kids',
 176: 'Living in Oblivion',
 177: 'Lord of Illusions',
 178: 'Love & Human Remains',
 179: 'Mad Love',
 180: 'Mallrats',
 181: 'Mighty Morphin Power Rangers: The Movie',
 182: 'Moonlight and Valentino',
 183: 'Mute Witness',
 184: 'Nadja',
 185: 'Net, The',
 186: 'Nine Months',
 187: 'Party Girl',
 188: 'Prophecy, The',
 189: 'Reckless',
 190: 'Safe',
 191: 'Scarlet Letter, The',
 192: 'Show, The',
 193: 'Showgirls',
 194: 'Smoke',
 195: 'Something to Talk About',
 196: 'Species',
 197: 'Stars Fell on Henrietta, The',
 198: 'Strange Days',
 199: 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les)',
 200: 'Tie That Binds, The',
 201: 'Three Wishes',
 202: 'Total Eclipse',
 203: 'To Wong Foo, Thanks for Everything! Julie Newmar',
 204: 'Under Siege 2: Dark Territory',
 205: 'Unstrung Heroes',
 206: 'Unzipped',
 207: 'Walk in the Clouds, A',
 208: 'Waterworld',
 209: "White Man's Burden",
 210: 'Wild Bill',
 211: 'Browning Version, The',
 212: 'Bushwhacked',
 213: 'Burnt by the Sun (Utomlyonnye solntsem)',
 214: 'Before the Rain (Pred dozhdot)',
 215: 'Before Sunrise',
 216: 'Billy Madison',
 217: 'Babysitter, The',
 218: 'Boys on the Side',
 219: 'Cure, The',
 220: 'Castle Freak',
 222: 'Circle of Friends',
 223: 'Clerks',
 224: 'Don Juan DeMarco',
 225: 'Disclosure',
 226: 'Dream Man',
 227: 'Drop Zone',
 228: 'Destiny Turns on the Radio',
 229: 'Death and the Maiden',
 230: 'Dolores Claiborne',
 231: 'Dumb & Dumber (Dumb and Dumber)',
 232: 'Eat Drink Man Woman (Yin shi nan nu)',
 233: 'Exotica',
 234: 'Exit to Eden',
 235: 'Ed Wood',
 236: 'French Kiss',
 237: 'Forget Paris',
 238: 'Far From Home: The Adventures of Yellow Dog',
 239: 'Goofy Movie, A',
 240: 'Hideaway',
 241: 'Fluke',
 242: 'Farinelli: il castrato',
 243: 'Gordy',
 244: 'Gumby: The Movie',
 245: 'Glass Shield, The',
 246: 'Hoop Dreams',
 247: 'Heavenly Creatures',
 248: 'Houseguest',
 249: 'Immortal Beloved',
 250: 'Heavyweights (Heavy Weights)',
 251: 'Hunted, The',
 252: 'I.Q.',
 253: 'Interview with the Vampire: The Vampire Chronicles',
 254: 'Jefferson in Paris',
 255: 'Jerky Boys, The',
 256: 'Junior',
 257: 'Just Cause',
 258: "Kid in King Arthur's Court, A",
 259: 'Kiss of Death',
 260: 'Star Wars: Episode IV - A New Hope',
 261: 'Little Women',
 262: 'Little Princess, A',
 263: 'Ladybird Ladybird',
 264: "Enfer, L'",
 265: 'Like Water for Chocolate (Como agua para chocolate)',
 266: 'Legends of the Fall',
 267: 'Major Payne',
 268: 'Little Odessa',
 269: 'My Crazy Life (Mi vida loca)',
 270: 'Love Affair',
 271: 'Losing Isaiah',
 272: 'Madness of King George, The',
 273: "Mary Shelley's Frankenstein (Frankenstein)",
 274: 'Man of the House',
 275: 'Mixed Nuts',
 276: 'Milk Money',
 277: 'Miracle on 34th Street',
 278: 'Miami Rhapsody',
 279: 'My Family',
 280: 'Murder in the First',
 281: "Nobody's Fool",
 282: 'Nell',
 283: 'New Jersey Drive',
 284: 'New York Cop (Nyû Yôku no koppu)',
 285: 'Beyond Bedlam',
 286: 'Nemesis 2: Nebula',
 287: 'Nina Takes a Lover',
 288: 'Natural Born Killers',
 289: 'Only You',
 290: 'Once Were Warriors',
 291: 'Poison Ivy II',
 292: 'Outbreak',
 293: 'Léon: The Professional (a.k.a. The Professional) (Léon)',
 294: 'Perez Family, The',
 295: "Pyromaniac's Love Story, A",
 296: 'Pulp Fiction',
 297: 'Panther',
 298: 'Pushing Hands (Tui shou)',
 299: 'Priest',
 300: 'Quiz Show',
 301: 'Picture Bride (Bijo photo)',
 302: 'Queen Margot (Reine Margot, La)',
 303: 'Quick and the Dead, The',
 304: 'Roommates',
 305: 'Ready to Wear (Pret-A-Porter)',
 306: 'Three Colors: Red (Trois couleurs: Rouge)',
 307: 'Three Colors: Blue (Trois couleurs: Bleu)',
 308: 'Three Colors: White (Trzy kolory: Bialy)',
 309: 'Red Firecracker, Green Firecracker (Pao Da Shuang Deng)',
 310: 'Rent-a-Kid',
 311: 'Relative Fear',
 312: 'Stuart Saves His Family',
 313: 'Swan Princess, The',
 314: 'Secret of Roan Inish, The',
 315: 'Specialist, The',
 316: 'Stargate',
 317: 'Santa Clause, The',
 318: 'Shawshank Redemption, The',
 319: 'Shallow Grave',
 320: 'Suture',
 321: 'Strawberry and Chocolate (Fresa y chocolate)',
 322: 'Swimming with Sharks',
 324: 'Sum of Us, The',
 325: "National Lampoon's Senior Trip",
 326: 'To Live (Huozhe)',
 327: 'Tank Girl',
 328: 'Tales from the Crypt Presents: Demon Knight',
 329: 'Star Trek: Generations',
 330: 'Tales from the Hood',
 331: 'Tom & Viv',
 332: 'Village of the Damned',
 333: 'Tommy Boy',
 334: 'Vanya on 42nd Street',
 335: 'Underneath',
 336: 'Walking Dead, The',
 337: "What's Eating Gilbert Grape",
 338: 'Virtuosity',
 339: 'While You Were Sleeping',
 340: 'War, The',
 341: 'Double Happiness',
 342: "Muriel's Wedding",
 343: 'Baby-Sitters Club, The',
 344: 'Ace Ventura: Pet Detective',
 345: 'Adventures of Priscilla, Queen of the Desert, The',
 346: 'Backbeat',
 347: 'Bitter Moon',
 348: 'Bullets Over Broadway',
 349: 'Clear and Present Danger',
 350: 'Client, The',
 351: 'Corrina, Corrina',
 352: 'Crooklyn',
 353: 'Crow, The',
 354: 'Cobb',
 355: 'Flintstones, The',
 356: 'Forrest Gump',
 357: 'Four Weddings and a Funeral',
 358: 'Higher Learning',
 359: 'I Like It Like That',
 360: 'I Love Trouble',
 361: 'It Could Happen to You',
 362: 'Jungle Book, The',
 363: 'Wonderful, Horrible Life of Leni Riefenstahl, The (Macht der Bilder: Leni Riefenstahl, Die)',
 364: 'Lion King, The',
 365: 'Little Buddha',
 366: "Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A)",
 367: 'Mask, The',
 368: 'Maverick',
 369: 'Mrs. Parker and the Vicious Circle',
 370: 'Naked Gun 33 1/3: The Final Insult',
 371: 'Paper, The',
 372: 'Reality Bites',
 373: 'Red Rock West',
 374: 'Richie Rich',
 375: 'Safe Passage',
 376: 'River Wild, The',
 377: 'Speed',
 378: 'Speechless',
 379: 'Timecop',
 380: 'True Lies',
 381: 'When a Man Loves a Woman',
 382: 'Wolf',
 383: 'Wyatt Earp',
 384: 'Bad Company',
 385: 'Man of No Importance, A',
 386: 'S.F.W.',
 387: 'Low Down Dirty Shame, A',
 388: 'Boys Life',
 389: 'Colonel Chabert, Le',
 390: 'Faster Pussycat! Kill! Kill!',
 391: "Jason's Lyric",
 392: 'Secret Adventures of Tom Thumb, The',
 393: 'Street Fighter',
 394: 'Coldblooded',
 395: 'Desert Winds',
 396: 'Fall Time',
 397: 'Fear, The',
 398: 'Frank and Ollie',
 399: 'Girl in the Cadillac',
 400: 'Homage',
 401: 'Mirage',
 402: 'Open Season',
 403: 'Two Crimes (Dos crímenes)',
 404: 'Brother Minister: The Assassination of Malcolm X',
 405: 'Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension)',
 406: 'Federal Hill',
 407: 'In the Mouth of Madness',
 408: '8 Seconds',
 409: 'Above the Rim',
 410: 'Addams Family Values',
 411: 'Martin Lawrence: You So Crazy',
 412: 'Age of Innocence, The',
 413: 'Airheads',
 414: 'Air Up There, The',
 415: 'Another Stakeout',
 416: 'Bad Girls',
 417: 'Barcelona',
 418: 'Being Human',
 419: 'Beverly Hillbillies, The',
 420: 'Beverly Hills Cop III',
 421: 'Black Beauty',
 422: 'Blink',
 423: 'Blown Away',
 424: 'Blue Chips',
 425: 'Blue Sky',
 426: 'Body Snatchers',
 427: 'Boxing Helena',
 428: 'Bronx Tale, A',
 429: 'Cabin Boy',
 430: 'Calendar Girl',
 431: "Carlito's Way",
 432: "City Slickers II: The Legend of Curly's Gold",
 433: 'Clean Slate',
 434: 'Cliffhanger',
 435: 'Coneheads',
 436: 'Color of Night',
 437: 'Cops and Robbersons',
 438: 'Cowboy Way, The',
 439: 'Dangerous Game',
 440: 'Dave',
 441: 'Dazed and Confused',
 442: 'Demolition Man',
 443: 'Endless Summer 2, The',
 444: 'Even Cowgirls Get the Blues',
 445: 'Fatal Instinct',
 446: 'Farewell My Concubine (Ba wang bie ji)',
 447: 'Favor, The',
 448: 'Fearless',
 449: 'Fear of a Black Hat',
 450: 'With Honors',
 451: 'Flesh and Bone',
 452: "Widows' Peak",
 453: 'For Love or Money',
 454: 'Firm, The',
 455: 'Free Willy',
 456: 'Fresh',
 457: 'Fugitive, The',
 458: 'Geronimo: An American Legend',
 459: 'Getaway, The',
 460: 'Getting Even with Dad',
 461: 'Go Fish',
 462: 'Good Man in Africa, A',
 463: 'Guilty as Sin',
 464: 'Hard Target',
 465: 'Heaven & Earth',
 466: 'Hot Shots! Part Deux',
 467: 'Live Nude Girls',
 468: 'Englishman Who Went Up a Hill But Came Down a Mountain, The',
 469: 'House of the Spirits, The',
 470: 'House Party 3',
 471: 'Hudsucker Proxy, The',
 472: "I'll Do Anything",
 473: 'In the Army Now',
 474: 'In the Line of Fire',
 475: 'In the Name of the Father',
 476: 'Inkwell, The',
 477: "What's Love Got to Do with It?",
 478: 'Jimmy Hollywood',
 479: 'Judgment Night',
 480: 'Jurassic Park',
 481: 'Kalifornia',
 482: 'Killing Zoe',
 483: 'King of the Hill',
 484: 'Lassie',
 485: 'Last Action Hero',
 486: 'Life with Mikey',
 487: 'Lightning Jack',
 488: 'M. Butterfly',
 489: 'Made in America',
 490: 'Malice',
 491: 'Man Without a Face, The',
 492: 'Manhattan Murder Mystery',
 493: 'Menace II Society',
 494: 'Executive Decision',
 495: 'In the Realm of the Senses (Ai no corrida)',
 496: 'What Happened Was...',
 497: 'Much Ado About Nothing',
 498: 'Mr. Jones',
 499: 'Mr. Wonderful',
 500: 'Mrs. Doubtfire',
 501: 'Naked',
 502: 'Next Karate Kid, The',
 503: 'New Age, The',
 504: 'No Escape',
 505: 'North',
 506: 'Orlando',
 507: 'Perfect World, A',
 508: 'Philadelphia',
 509: 'Piano, The',
 510: 'Poetic Justice',
 511: 'Program, The',
 512: 'Puppet Masters, The',
 513: 'Radioland Murders',
 514: 'Ref, The',
 515: 'Remains of the Day, The',
 516: 'Renaissance Man',
 517: 'Rising Sun',
 518: 'Road to Wellville, The',
 519: 'RoboCop 3',
 520: 'Robin Hood: Men in Tights',
 521: 'Romeo Is Bleeding',
 522: 'Romper Stomper',
 523: 'Ruby in Paradise',
 524: 'Rudy',
 525: 'Saint of Fort Washington, The',
 526: 'Savage Nights (Nuits fauves, Les)',
 527: "Schindler's List",
 528: 'Scout, The',
 529: 'Searching for Bobby Fischer',
 530: 'Second Best',
 531: 'Secret Garden, The',
 532: 'Serial Mom',
 533: 'Shadow, The',
 534: 'Shadowlands',
 535: 'Short Cuts',
 536: 'Simple Twist of Fate, A',
 537: 'Sirens',
 538: 'Six Degrees of Separation',
 539: 'Sleepless in Seattle',
 540: 'Sliver',
 541: 'Blade Runner',
 542: 'Son in Law',
 543: 'So I Married an Axe Murderer',
 544: 'Striking Distance',
 545: 'Harem',
 546: 'Super Mario Bros.',
 547: 'Surviving the Game',
 548: 'Terminal Velocity',
 549: 'Thirty-Two Short Films About Glenn Gould',
 550: 'Threesome',
 551: 'Nightmare Before Christmas, The',
 552: 'Three Musketeers, The',
 553: 'Tombstone',
 554: 'Trial by Jury',
 555: 'True Romance',
 556: 'War Room, The',
 558: 'Pagemaster, The',
 559: 'Paris, France',
 560: 'Beans of Egypt, Maine, The',
 561: 'Killer (Bulletproof Heart)',
 562: 'Welcome to the Dollhouse',
 563: 'Germinal',
 564: 'Chasers',
 565: 'Cronos',
 566: 'Naked in New York',
 567: 'Kika',
 568: 'Bhaji on the Beach',
 569: 'Little Big League',
 570: 'Slingshot, The (Kådisbellan)',
 571: 'Wedding Gift, The',
 572: 'Foreign Student',
 573: 'Ciao, Professore! (Io speriamo che me la cavo)',
 574: 'Spanking the Monkey',
 575: 'Little Rascals, The',
 576: 'Fausto',
 577: 'Andre',
 579: 'Escort, The (Scorta, La)',
 580: 'Princess Caraboo',
 581: 'Celluloid Closet, The',
 582: 'Métisse (Café au Lait)',
 583: 'Dear Diary (Caro Diario)',
 584: "I Don't Want to Talk About It (De eso no se habla)",
 585: 'Brady Bunch Movie, The',
 586: 'Home Alone',
 587: 'Ghost',
 588: 'Aladdin',
 589: 'Terminator 2: Judgment Day',
 590: 'Dances with Wolves',
 591: 'Tough and Deadly',
 592: 'Batman',
 593: 'Silence of the Lambs, The',
 594: 'Snow White and the Seven Dwarfs',
 595: 'Beauty and the Beast',
 596: 'Pinocchio',
 597: 'Pretty Woman',
 598: 'Window to Paris (Okno v Parizh)',
 599: 'Wild Bunch, The',
 600: 'Love and a .45',
 601: "Wooden Man's Bride, The (Yan shen)",
 602: 'Great Day in Harlem, A',
 603: 'Bye Bye, Love',
 604: 'Criminals',
 605: 'One Fine Day',
 606: 'Candyman: Farewell to the Flesh',
 607: 'Century',
 608: 'Fargo',
 609: 'Homeward Bound II: Lost in San Francisco',
 610: 'Heavy Metal',
 611: 'Hellraiser: Bloodline',
 612: 'Pallbearer, The',
 613: 'Jane Eyre',
 614: 'Loaded',
 615: 'Bread and Chocolate (Pane e cioccolata)',
 616: 'Aristocats, The',
 617: 'Flower of My Secret, The (La flor de mi secreto)',
 618: 'Two Much',
 619: 'Ed',
 620: 'Scream of Stone (Cerro Torre: Schrei aus Stein)',
 621: 'My Favorite Season',
 623: 'Modern Affair, A',
 624: 'Condition Red (Beyond the Law)',
 625: 'Asfour Stah',
 626: 'Thin Line Between Love and Hate, A',
 627: 'Last Supper, The',
 628: 'Primal Fear',
 629: 'Rude',
 630: 'Carried Away',
 631: 'All Dogs Go to Heaven 2',
 632: 'Land and Freedom (Tierra y libertad)',
 633: 'Denise Calls Up',
 634: 'Theodore Rex',
 635: 'Family Thing, A',
 636: 'Frisk',
 637: 'Sgt. Bilko',
 638: 'Jack and Sarah',
 639: 'Girl 6',
 640: 'Diabolique',
 641: 'Little Indian, Big City (Un indien dans la ville)',
 642: 'Roula',
 643: 'Peanuts - Die Bank zahlt alles',
 644: 'Happy Weekend',
 645: 'Nelly & Monsieur Arnaud',
 647: 'Courage Under Fire',
 648: 'Mission: Impossible',
 649: 'Cold Fever (Á köldum klaka)',
 650: 'Moll Flanders',
 651: 'Superweib, Das',
 652: '301, 302 (301/302)',
 653: 'Dragonheart',
 654: 'And Nobody Weeps for Me (Und keiner weint mir nach)',
 655: "My Mother's Courage (Mutters Courage)",
 656: 'Eddie',
 657: 'Yankee Zulu',
 658: "Billy's Holiday",
 659: 'Purple Noon (Plein soleil)',
 660: 'August',
 661: 'James and the Giant Peach',
 662: 'Fear',
 663: 'Kids in the Hall: Brain Candy',
 664: 'Faithful',
 665: 'Underground',
 666: 'All Things Fair (Lust och fägring stor)',
 667: 'Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite)',
 668: 'Song of the Little Road (Pather Panchali)',
 670: 'World of Apu, The (Apur Sansar)',
 671: 'Mystery Science Theater 3000: The Movie',
 672: 'Tarantella',
 673: 'Space Jam',
 674: 'Barbarella',
 675: 'Hostile Intentions',
 676: 'They Bite',
 678: 'Some Folks Call It a Sling Blade',
 679: 'Run of the Country, The',
 680: 'Alphaville (Alphaville, une étrange aventure de Lemmy Caution)',
 681: 'Coup de torchon (Clean Slate)',
 682: 'Tigrero: A Film That Was Never Made',
 683: "Eye of Vichy, The (Oeil de Vichy, L')",
 684: 'Windows',
 685: "It's My Party",
 687: 'Country Life',
 688: 'Operation Dumbo Drop',
 690: 'Promise, The (Versprechen, Das)',
 691: 'Mrs. Winterbourne',
 692: 'Solo',
 693: 'Under the Domim Tree (Etz Hadomim Tafus)',
 694: 'Substitute, The',
 695: 'True Crime',
 696: 'Butterfly Kiss',
 697: 'Feeling Minnesota',
 698: 'Delta of Venus',
 699: 'To Cross the Rubicon',
 700: 'Angus',
 701: 'Daens',
 702: 'Faces',
 703: 'Boys',
 704: 'Quest, The',
 705: 'Cosi',
 706: 'Sunset Park',
 707: 'Mulholland Falls',
 708: 'Truth About Cats & Dogs, The',
 709: 'Oliver & Company',
 710: 'Celtic Pride',
 711: 'Flipper',
 712: 'Captives',
 713: 'Of Love and Shadows',
 714: 'Dead Man',
 715: 'Horseman on the Roof, The (Hussard sur le toit, Le)',
 716: 'Switchblade Sisters',
 717: 'Mouth to Mouth (Boca a boca)',
 718: 'Visitors, The (Visiteurs, Les)',
 719: 'Multiplicity',
 720: 'Wallace & Gromit: The Best of Aardman Animation',
 721: 'Halfmoon (Paul Bowles - Halbmond)',
 722: 'Haunted World of Edward D. Wood Jr., The',
 723: 'Two Friends',
 724: 'Craft, The',
 725: 'Great White Hype, The',
 726: 'Last Dance',
 727: 'War Stories',
 728: 'Cold Comfort Farm',
 729: 'Institute Benjamenta, or This Dream People Call Human Life',
 730: 'Low Life',
 731: "Heaven's Prisoners",
 732: 'Original Gangstas',
 733: 'Rock, The',
 734: 'Getting Away With Murder',
 735: 'Cemetery Man (Dellamorte Dellamore)',
 736: 'Twister',

In [ ]:
import json

with open("/content/drive/MyDrive/data_movie/data_movie/filtering/movie_mapper.json", "w") as f:
  json.dump(mapper_id_to_movie, f)

In [ ]:
X.to_csv("/content/drive/MyDrive/data_movie/data_movie/filtering/user_item_interaction.csv")

decomposed_matrix = pd.DataFrame(decomposed_matrix)
decomposed_matrix.to_csv("/content/drive/MyDrive/data_movie/data_movie/filtering/decomposed_matrix.csv")

KeyboardInterrupt

In [ ]:
import pickle as pkl

with open("/content/drive/MyDrive/data_movie/data_movie/filtering/SVD.pkl", "wb") as f:
  pkl.dump(SVD, f)

In [ ]:
df_recom

          userId  movieId  rating
0              1        2     3.5
1              1       29     3.5
2              1       32     3.5
3              1       47     3.5
4              1       50     3.5
...          ...      ...     ...
20000258  138493    68954     4.5
20000259  138493    69526     4.5
20000260  138493    69644     3.0
20000261  138493    70286     5.0
20000262  138493    71619     2.5

[20000263 rows x 3 columns]

In [ ]:
import pandas as pd
import ast

# Convert string → lis1t (movies dataframe)
df_movies['genres'] = df_movies['genres'].apply(ast.literal_eval)

# Merge ratings with movies to bring userId + genres together
df = df_recom.merge(df_movies[['movieId', 'genres']], on='movieId', how='inner')

# Explode genres
df_exploded = df.explode('genres')

# Keep only required columns
user_genre_df = df_exploded[['userId', 'genres']].rename(columns={'genres': 'genre'})

print(user_genre_df.head())

   userId      genre
0       1  Adventure
0       1   Children
0       1    Fantasy
1       1  Adventure
1       1      Drama

In [ ]:
user_genre_df.genre.unique()

array(['Adventure', 'Children', 'Fantasy', 'Drama', 'Mystery', 'Sci-Fi',
       'Thriller', 'Crime', 'Action', 'Comedy', 'Romance', 'War',
       'Horror', 'Musical', 'Western', 'Animation', 'IMAX', 'Film-Noir',
       'Documentary', '(no genres listed)'], dtype=object)

In [ ]:
user_genre_df = user_genre_df[user_genre_df['genre']!= "(no genres listed)"]

In [ ]:
user_genre_df.head()

   userId      genre
0       1  Adventure
0       1   Children
0       1    Fantasy
1       1  Adventure
1       1      Drama

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
user_genre_df['genre'] = le.fit_transform(user_genre_df['genre'])

In [ ]:
import pickle as pkl

In [ ]:
with open("/content/drive/MyDrive/data_movie/data_movie/filtering/label_encoder.pkl", "wb") as f:
  pkl.dump(le, f)

In [ ]:
user_genre_df.head()

   userId  genre
0       1      1
1       1      3
2       1      8
3       1      1
4       1      7

In [ ]:
user_genre_df.reset_index(inplace=True, drop=True)

In [ ]:
user_genre_df.head()

   userId  genre
0       1      1
1       1      3
2       1      8
3       1      1
4       1      7

In [ ]:
user_genre_counts = (
    user_genre_df.groupby(['userId', 'genre'])
      .size()
      .reset_index(name='count')
)

In [ ]:
user_genre_counts['normalized'] = (
    user_genre_counts.groupby('userId')['count']
    .transform(lambda x: x / x.sum())
)

In [ ]:
user_genre_counts

         userId  genre  count  normalized
0             1      0     66    0.127907
1             1      1     73    0.141473
2             1      2     10    0.019380
3             1      3     19    0.036822
4             1      4     41    0.079457
...         ...    ...    ...         ...
2268309  138493     14     78    0.069643
2268310  138493     15     70    0.062500
2268311  138493     16     87    0.077679
2268312  138493     17     12    0.010714
2268313  138493     18      5    0.004464

[2268314 rows x 4 columns]

In [ ]:
user_embedding = user_genre_counts.pivot(
    index='userId',
    columns='genre',
    values='normalized'
).fillna(0)

In [ ]:
user_embedding.head()

genre,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
userId,,,,,,,,,,,,,,,,,,,
1,0.127907,0.141473,0.019380,0.036822,0.079457,0.040698,0.00000,0.083333,0.133721,0.000000,0.087209,0.003876,0.005814,0.034884,0.021318,0.077519,0.081395,0.017442,0.007752
2,0.127517,0.114094,0.006711,0.006711,0.067114,0.006711,0.00000,0.127517,0.006711,0.006711,0.120805,0.006711,0.013423,0.026846,0.040268,0.154362,0.127517,0.026846,0.013423
3,0.123232,0.101010,0.008081,0.020202,0.105051,0.042424,0.00202,0.117172,0.040404,0.002020,0.064646,0.000000,0.012121,0.022222,0.032323,0.187879,0.101010,0.012121,0.006061
4,0.158537,0.073171,0.024390,0.048780,0.134146,0.073171,0.00000,0.097561,0.036585,0.000000,0.000000,0.000000,0.024390,0.036585,0.048780,0.060976,0.158537,0.012195,0.012195
5,0.098361,0.114754,0.032787,0.060109,0.131148,0.038251,0.00000,0.147541,0.060109,0.000000,0.005464,0.016393,0.043716,0.010929,0.087432,0.054645,0.081967,0.005464,0.010929

In [ ]:
users = list(user_embedding.index)

In [ ]:
import dill
import pickle as pkl

In [ ]:
from sklearn.neighbors import NearestNeighbors

neighbor_finder = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=10, n_jobs=-1)

In [ ]:
from sklearn.decomposition import PCA


pca = PCA(n_components=10)

In [ ]:
pca.fit(user_embedding)

PCA(n_components=10)

In [ ]:
### preserve the index as the user ids

df_embedding_reduced = pd.DataFrame(pca.transform(user_embedding))

In [ ]:
df_embedding_reduced.index = users

In [ ]:
df_embedding_reduced.head()

,0,1,2,3,4,5,6,7,8,9
1,-0.121408,0.037373,-0.057034,-0.049376,0.030859,0.007782,0.045642,-0.023735,0.069537,-0.016917
2,-0.113423,-0.033991,-0.021861,-0.024511,0.110582,0.060051,0.021773,0.019577,-0.013977,0.034098
3,-0.105119,0.003131,-0.015898,-0.011607,0.109503,0.011332,-0.035072,0.001092,-0.015161,-0.000027
4,-0.084126,0.005451,0.044079,-0.003286,-0.039320,0.003362,-0.013122,0.007638,-0.024800,-0.013550
5,-0.009260,0.047108,-0.045582,0.008549,-0.020132,0.012514,-0.005141,0.011501,0.002987,-0.007449

In [ ]:
df_embedding_reduced.to_csv("/content/drive/MyDrive/data_movie/data_movie/filtering/user_embedding.csv")

In [ ]:
user_list = list(df_embedding_reduced.index)

with open("/content/drive/MyDrive/data_movie/data_movie/filtering/user_list.pkl", "wb") as f:
  pkl.dump(user_list, f)

In [ ]:
neighbor_finder.fit(df_embedding_reduced)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=10)

In [ ]:
with open("/content/drive/MyDrive/data_movie/data_movie/filtering/neighbor_finder.pkl", "wb") as f:
  pkl.dump(neighbor_finder, f)

In [ ]:
with open("/content/drive/MyDrive/data_movie/data_movie/filtering/pca.pkl", "wb") as f:
  pkl.dump(pca, f)

In [ ]:
import pandas as pd

In [ ]:
df_recom = pd.read_csv("/content/drive/MyDrive/data_movie/data_movie/ratings.csv")

In [ ]:
df_recom.tail()

          userId  movieId  rating
20000258  138493    68954     4.5
20000259  138493    69526     4.5
20000260  138493    69644     3.0
20000261  138493    70286     5.0
20000262  138493    71619     2.5

In [ ]:
### Find top rated movies for each user

user_and_top_5_movies = user_top5 = (
    df_recom
    .sort_values(['userId', 'rating'], ascending=[True, False])
    .groupby('userId')
    .head(5))

In [ ]:
user_and_top_5_movies.tail()

          userId  movieId  rating
19999903  138493      235     5.0
19999906  138493      288     5.0
19999912  138493      356     5.0
19999922  138493      508     5.0
19999923  138493      527     5.0

In [ ]:
user_and_top_5_movies

          userId  movieId  rating
131            1     4993     5.0
142            1     5952     5.0
158            1     7153     5.0
170            1     8507     5.0
30             1     1196     4.5
...          ...      ...     ...
19999903  138493      235     5.0
19999906  138493      288     5.0
19999912  138493      356     5.0
19999922  138493      508     5.0
19999923  138493      527     5.0

[692465 rows x 3 columns]

In [ ]:
user_and_top_5_movies

          userId  movieId  rating
131            1     4993     5.0
142            1     5952     5.0
158            1     7153     5.0
170            1     8507     5.0
30             1     1196     4.5
...          ...      ...     ...
19999903  138493      235     5.0
19999906  138493      288     5.0
19999912  138493      356     5.0
19999922  138493      508     5.0
19999923  138493      527     5.0

[692465 rows x 3 columns]

In [ ]:
df_comb = user_and_top_5_movies.reset_index()

In [ ]:
df_comb.head()

   index  userId  movieId  rating
0    131       1     4993     5.0
1    142       1     5952     5.0
2    158       1     7153     5.0
3    170       1     8507     5.0
4     30       1     1196     4.5

In [ ]:
df_comb.tail()

           index  userId  movieId  rating
692460  19999903  138493      235     5.0
692461  19999906  138493      288     5.0
692462  19999912  138493      356     5.0
692463  19999922  138493      508     5.0
692464  19999923  138493      527     5.0

In [ ]:
df_comb.drop("index", inplace=True, axis=1)

In [ ]:
df_movie_names = df_movies[["movieId", "movie_name"]]

In [ ]:
df_movie_names

       movieId                   movie_name
0            1                    Toy Story
1            2                      Jumanji
2            3             Grumpier Old Men
3            4            Waiting to Exhale
4            5  Father of the Bride Part II
...        ...                          ...
27273   131254        Kein Bund für's Leben
27274   131256       Feuer, Eis & Dosenbier
27275   131258                  The Pirates
27276   131260                 Rentun Ruusu
27277   131262                    Innocence

[27278 rows x 2 columns]

In [ ]:
df_final_recom = df_comb.merge(df_movie_names, left_on="movieId", right_on="movieId", how="inner")

In [ ]:
df_final_recom.head()

   userId  movieId  rating                                         movie_name
0       1     4993     5.0  Lord of the Rings: The Fellowship of the Ring,...
1       1     5952     5.0             Lord of the Rings: The Two Towers, The
2       1     7153     5.0     Lord of the Rings: The Return of the King, The
3       1     8507     5.0                                             Freaks
4       1     1196     4.5     Star Wars: Episode V - The Empire Strikes Back

In [ ]:
df_final_recom.tail()

        userId  movieId  rating            movie_name
692460  138493      235     5.0               Ed Wood
692461  138493      288     5.0  Natural Born Killers
692462  138493      356     5.0          Forrest Gump
692463  138493      508     5.0          Philadelphia
692464  138493      527     5.0      Schindler's List

In [ ]:
### Create list for movies for each user

user_movies = (
    df_final_recom.groupby('userId')['movie_name']
      .apply(list)
      .reset_index(name='movie_list')
)

In [ ]:
user_movies.head()

   userId                                         movie_list
0       1  [Lord of the Rings: The Fellowship of the Ring...
1       2  [Mr. Holland's Opus, From Dusk Till Dawn, Star...
2       3  [Usual Suspects, The, Kids, Clerks, Star Wars:...
3       4  [Firm, The, Rock, The, GoldenEye, Client, The,...
4       5  [American President, The, Mr. Holland's Opus, ...

In [ ]:
user_movies.tail()

        userId                                         movie_list
138488  138489  [Shawshank Redemption, The, Godfather, The, Ca...
138489  138490  [Twelve Monkeys (a.k.a. 12 Monkeys), Babe, Tax...
138490  138491  [Yellow Submarine, Girl, Interrupted, Doors, T...
138491  138492  [Dazed and Confused, Godfather, The, Blues Bro...
138492  138493  [Ed Wood, Natural Born Killers, Forrest Gump, ...

In [ ]:
user_movies[user_movies['userId']==59563]

       userId                                         movie_list
59562   59563  [Matrix, The, Memento, Amelie (Fabuleux destin...

In [ ]:
user_movies.to_csv("/content/drive/MyDrive/data_movie/data_movie/filtering/user_top_pref.csv", index=False)

In [ ]:
df = df_recom.merge(df_movies[['movieId', 'genres']], on='movieId', how='inner')

In [ ]:
df.head()

   userId  movieId  rating                                             genres
0       1        2     3.5               ['Adventure', 'Children', 'Fantasy']
1       1       29     3.5  ['Adventure', 'Drama', 'Fantasy', 'Mystery', '...
2       1       32     3.5                  ['Mystery', 'Sci-Fi', 'Thriller']
3       1       47     3.5                            ['Mystery', 'Thriller']
4       1       50     3.5                   ['Crime', 'Mystery', 'Thriller']

In [ ]:
df.drop(["userId","interaction"], axis=1, inplace=True)

In [ ]:
df.head()

In [ ]:
movie_map = df_movies[["movieId", "movie_name"]]

In [ ]:
df_movie_final = pd.merge(df, movie_map, left_on="movieId", right_on="movieId", how="inner")

In [ ]:
df_movie_final.head()

In [ ]:
popular_movies = (
    df_movie_final.groupby('movieId')
      .agg(avg_rating=('rating', 'mean'), count=('rating', 'count'))
      .reset_index()
)

# Filter strong candidates
popular_movies = popular_movies[
    (popular_movies['count'] > 50) & (popular_movies['avg_rating'] >= 3.5)
]

In [ ]:
popular_movies

       movieId  avg_rating  count
0            1    3.921240  49695
5            6    3.834930  23899
10          11    3.667713  18162
15          16    3.787455  17394
16          17    3.968573  20667
...        ...         ...    ...
24616   117533    3.895062     81
24685   117881    3.730769     65
24829   118700    3.727273     88
24872   118900    3.674312    109
24934   119145    3.632075    159

[3961 rows x 3 columns]

In [ ]:
popular_movies = popular_movies.merge(
   df_movies[['movieId', 'movie_name', 'genres']],
    on='movieId'
)

In [ ]:
popular_movies

,movieId,avg_rating,count,movie_name,genres
0,1,3.921240,49695,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]"
1,6,3.834930,23899,Heat,"[Action, Crime, Thriller]"
2,11,3.667713,18162,"American President, The","[Comedy, Drama, Romance]"
3,16,3.787455,17394,Casino,"[Crime, Drama]"
4,17,3.968573,20667,Sense and Sensibility,"[Drama, Romance]"
...,...,...,...,...,...
3956,117533,3.895062,81,Citizenfour,[Documentary]
3957,117881,3.730769,65,Still Alice,[Drama]
3958,118700,3.727273,88,Selma,[Drama]
3959,118900,3.674312,109,Wild,[Drama]
3960,119145,3.632075,159,Kingsman: The Secret Service,"[Action, Adventure, Comedy, Crime]"

In [ ]:
cold_start_candidates = (
    popular_movies
    .explode('genres')
    .sort_values(['genres', 'avg_rating', 'count'], ascending=[True, False, False])
    .groupby('genres')
    .head(2)   # 2 movies per genre
)

In [ ]:
final_movies = cold_start_candidates.sample(30, random_state=42)

In [ ]:
df_data = final_movies[['movieId', 'movie_name', 'genres']]

In [ ]:
df_data.to_csv("/content/drive/MyDrive/data_movie/data_movie/filtering/Cold_starter.csv")