In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/data_movie/data_movie/final_database.csv")

In [ ]:
df.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
0,The Shawshank Redemption,1994,A,142,['Drama'],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175,"['Crime', ' Drama']",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152,"['Action', ' Crime', ' Drama']",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202,"['Crime', ' Drama']",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96,"['Crime', ' Drama']",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df.tail()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
5579,El Mariachi,1992,NaN,81,"['Action', 'Crime', 'Thriller']",6.6,El Mariachi just wants to play his guitar and ...,NaN,2040920,"['Carlos Gallardo', 'Jaime de Hoyos', 'Peter M..."
5580,Newlyweds,2011,NaN,85,"['Comedy', 'Romance']",5.9,A newlywed couple's honeymoon is upended by th...,NaN,0,"['Edward Burns', 'Kerry Bishé', 'Marsha Dietle..."
5581,"Signed, Sealed, Delivered",2013,NaN,120,"['Comedy', 'Drama', 'Romance', 'TV Movie']",7.0,"""Signed, Sealed, Delivered"" introduces a dedic...",NaN,0,"['Eric Mabius', 'Kristin Booth', 'Daphne Zunig..."
5582,Shanghai Calling,2012,NaN,98,[],5.7,When ambitious New York attorney Sam is sent t...,NaN,0,"['Daniel Henney', 'Eliza Coupe', 'Bill Paxton'..."
5583,My Date with Drew,2005,NaN,90,['Documentary'],6.3,Ever since the second grade when he first saw ...,NaN,0,"['Drew Barrymore', 'Brian Herzlinger', 'Corey ..."

In [ ]:
df.Certificate.fillna("Not Provided", inplace=True)

In [ ]:
df.Director.fillna("Not Provided", inplace=True)

In [ ]:
df.tail()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
5579,El Mariachi,1992,Not Provided,81,"['Action', 'Crime', 'Thriller']",6.6,El Mariachi just wants to play his guitar and ...,Not Provided,2040920,"['Carlos Gallardo', 'Jaime de Hoyos', 'Peter M..."
5580,Newlyweds,2011,Not Provided,85,"['Comedy', 'Romance']",5.9,A newlywed couple's honeymoon is upended by th...,Not Provided,0,"['Edward Burns', 'Kerry Bishé', 'Marsha Dietle..."
5581,"Signed, Sealed, Delivered",2013,Not Provided,120,"['Comedy', 'Drama', 'Romance', 'TV Movie']",7.0,"""Signed, Sealed, Delivered"" introduces a dedic...",Not Provided,0,"['Eric Mabius', 'Kristin Booth', 'Daphne Zunig..."
5582,Shanghai Calling,2012,Not Provided,98,[],5.7,When ambitious New York attorney Sam is sent t...,Not Provided,0,"['Daniel Henney', 'Eliza Coupe', 'Bill Paxton'..."
5583,My Date with Drew,2005,Not Provided,90,['Documentary'],6.3,Ever since the second grade when he first saw ...,Not Provided,0,"['Drew Barrymore', 'Brian Herzlinger', 'Corey ..."

In [ ]:
import re

def clean_text(desc):
  modified_text = desc.replace("<ul>", "").replace("</ul>", "").replace("<li>", "").replace("</li>", ",").replace("<br>", ".")
  final = re.sub(r'<[^>]*>', '', modified_text).replace(". .",".")
  return final

In [ ]:
df["Overview"] = df["Overview"].apply(clean_text)

In [ ]:
!pip install sentence-transformers chromadb

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Collecting chromadb
  Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.4.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.42.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.80.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.1)
Collecting opentelemetry-exporter-otlp-proto-common==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.6)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 62.1 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 20.2 MB/s eta 0:00:00
Downloading build-1.4.2-py3-none-any.whl (24 kB)
Downloading kubernetes-35.0.0-py2.py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 81.8 MB/s eta 0:00:00
Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 70.5 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl (20 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 6.1 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 11.6 MB/s eta 0:00:00
Downloading opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 kB 3.8 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 16.6 MB/s eta 0:00:00
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 3.8 MB/s eta 0:00:00
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.3 MB/s eta 0:00:00
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pypika, durationpy, pyproject_hooks, pybase64, opentelemetry-proto, bcrypt, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, onnxruntime, build, opentelemetry-semantic-conventions, kubernetes, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:
      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.38.0
    Uninstalling opentelemetry-sdk-1.38.0:
      Successfully uninstalled opentelemetry-sdk-1.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
google-adk 1.28.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.40.0 which is incompatible.
google-adk 1.28.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
Successfully installed bcrypt-5.0.0 build-1.4.2 chromadb-1.5.5 durationpy-0.10 kubernetes-35.0.0 onnxruntime-1.24.4 opentelemetry-api-1.40.0 opentelemetry-exporter-otlp-proto-common-1.40.0 opentelemetry-exporter-otlp-proto-grpc-1.40.0 opentelemetry-proto-1.40.0 opentelemetry-sdk-1.40.0 opentelemetry-semantic-conventions-0.61b0 pybase64-1.4.3 pypika-0.51.1 pyproject_hooks-1.2.0

In [ ]:
from sentence_transformers import SentenceTransformer, util
from sentence_transformers import SentenceTransformer

### Initializing sentence embedding model
model_name = "all-MiniLM-L6-v2"
embedder = SentenceTransformer(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
### Initializing chroma db client
import chromadb

chroma_db_path = '/content/drive/MyDrive/data_movie/data_movie/ChromaDBData'

client = chromadb.PersistentClient(path=chroma_db_path)

In [ ]:
df.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
0,The Shawshank Redemption,1994,A,142,['Drama'],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175,"['Crime', ' Drama']",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152,"['Action', ' Crime', ' Drama']",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202,"['Crime', ' Drama']",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96,"['Crime', ' Drama']",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df["metadata"] = df.apply(lambda x: {
    "Title": x["Title"],
    "Released_Year": x["Released_Year"],
    "Genre": x["Genre"],
    "Rating": x["Rating"],
    "Overview": x["Overview"],
    "Director": x["Director"],
    "Cast": x["Cast"],
}, axis=1)

In [ ]:
### Creating search text for seaching

def get_search_text(metadata):
  text = ""
  ### Adding Product name
  text += metadata["Title"] + ":"
  ### Adding product description
  text += metadata["Overview"] + " "

  if len(text) == 0:
    text = "No available description"

  return text

In [ ]:
df["text_search"] = df["metadata"].apply(get_search_text)

In [ ]:
df.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast,metadata,text_search
0,The Shawshank Redemption,1994,A,142,['Drama'],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'...","{'Title': 'The Shawshank Redemption', 'Release...",The Shawshank Redemption:Two imprisoned men bo...
1,The Godfather,1972,A,175,"['Crime', ' Drama']",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '...","{'Title': 'The Godfather', 'Released_Year': '1...",The Godfather:An organized crime dynasty's agi...
2,The Dark Knight,2008,UA,152,"['Action', ' Crime', ' Drama']",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh...","{'Title': 'The Dark Knight', 'Released_Year': ...",The Dark Knight:When the menace known as the J...
3,The Godfather: Part II,1974,A,202,"['Crime', ' Drama']",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall...","{'Title': 'The Godfather: Part II', 'Released_...",The Godfather: Part II:The early life and care...
4,12 Angry Men,1957,U,96,"['Crime', ' Drama']",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'...","{'Title': '12 Angry Men', 'Released_Year': '19...",12 Angry Men:A jury holdout attempts to preven...

In [ ]:
def generate_embeddings(texts):
    embeddings = embedder.encode(texts, convert_to_tensor=False)
    return embeddings

In [ ]:
df["embeddings"] = df["text_search"].apply(generate_embeddings)

In [ ]:
df.to_csv("/content/drive/MyDrive/data_movie/data_movie/data_movie_embedded.csv", index=False)

In [ ]:
collection = client.get_or_create_collection(name='Fashion_Collection')

In [ ]:
ids = [str(i) for i in range(len(df))]

In [ ]:
max_batch_size = 5000  # safe margin

for i in range(0, len(df), max_batch_size):
    batch = df.iloc[i:i+max_batch_size]

    collection.add(
        embeddings=batch['embeddings'].tolist(),
        documents=batch['text_search'].tolist(),
        metadatas=batch['metadata'].tolist(),
        ids=ids[i:i+max_batch_size]
    )

In [ ]:
### Creating cache

In [ ]:
cache_collection_name = 'Cache'

In [ ]:
cache_collection = client.get_or_create_collection(name=cache_collection_name)

In [ ]:
## Semantic search with cache

In [ ]:
query = input("Please enter your query?")

Please enter your query?movies like shwashank redemption

In [ ]:
cache_results = cache_collection.query(
    query_texts = [query],
    n_results = 2
)

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:01<00:00, 53.7MiB/s]

In [ ]:
cache_results

{'ids': [[]],
 'embeddings': None,
 'documents': [[]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[]],
 'distances': [[]]}

In [ ]:

results = collection.query(
query_texts=query,
n_results=10
)
results.items()

dict_items([('ids', [['4831', '4919', '0', '5421', '6', '5072', '284', '4615', '3429', '1924']]), ('embeddings', None), ('documents', [["Redemption Road:A Tennessee-set drama focused on an individual's spiritual redemption. ", "Gangster's Paradise: Jerusalema:This South African movie tracks the rise of a once-petty criminal to the heights of the criminal underworld. After cutting his teeth on hijacking, before moving onto bigger game, an ambitious man hits a setback when most of his gang are shot. ", 'The Shawshank Redemption:Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. ', 'Love and Other Catastrophes:A day in the life of two film-school students trying to find love and another house-mate. ', 'Pulp Fiction:The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption. ', 'Da Sweet Blood of Jesus:A movie about human beings who are addicted to blood. ', 'Sin City:A movie that explores the dark and miserable town, Basin City, tells the story of three different people, all caught up in violent corruption. ', "In Cold Blood:A 1967 film based on Truman Capote's book of the same name. After a botched robbery results in the brutal murder of a rural family, two drifters elude police, in the end coming to terms with their own mortality and the repercussions of their vile atrocity. ", 'Ong Bak 2:Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father. ', "The Warrior's Way:An Asian assassin (Dong-gun Jang) is forced to hide in a small town in the American Badlands. Also starring Kate Bosworth, Danny Huston, Tony Cox and Academy Award winner Geoffrey Rush. "]]), ('uris', None), ('included', ['metadatas', 'documents', 'distances']), ('data', None), ('metadatas', [[{'Rating': 4.7, 'Released_Year': '2011', 'Cast': "['Michael Clarke Duncan', 'Kiele Sanchez', 'Taryn Manning', 'Luke Perry', 'Tom Skerritt']", 'Director': 'Not Provided', 'Genre': "['Drama']", 'Overview': "A Tennessee-set drama focused on an individual's spiritual redemption.", 'Title': 'Redemption Road'}, {'Cast': "['Daniel Buckland', 'Robert Hobbs', 'Rapulana Seiphemo', 'Jeffrey Zekele', 'Ronnie Nyakale']", 'Released_Year': '2008', 'Genre': "['Drama', 'Action', 'Crime', 'Foreign']", 'Director': 'Not Provided', 'Rating': 6.8, 'Title': "Gangster's Paradise: Jerusalema", 'Overview': 'This South African movie tracks the rise of a once-petty criminal to the heights of the criminal underworld. After cutting his teeth on hijacking, before moving onto bigger game, an ambitious man hits a setback when most of his gang are shot.'}, {'Rating': 9.3, 'Director': 'Frank Darabont', 'Genre': "['Drama']", 'Cast': "['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler']", 'Released_Year': '1994', 'Overview': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Title': 'The Shawshank Redemption'}, {'Rating': 5.8, 'Released_Year': '1996', 'Director': 'Not Provided', 'Cast': '[\'Matt Day\', \'Matthew Dyktynski\', \'Alice Garner\', "Frances O\'Connor", \'Radha Mitchell\']', 'Overview': 'A day in the life of two film-school students trying to find love and another house-mate.', 'Genre': "['Comedy', 'Romance']", 'Title': 'Love and Other Catastrophes'}, {'Genre': "['Crime', ' Drama']", 'Released_Year': '1994', 'Director': 'Quentin Tarantino', 'Rating': 8.9, 'Cast': "['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis']", 'Overview': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Title': 'Pulp Fiction'}, {'Director': 'Not Provided', 'Title': 'Da Sweet Blood of Jesus', 'Overview': 'A movie about human beings who are addicted to blood.', 'Rating': 4.1, 'Cast': "['Felicia Pearson', 'Zaraah Abrahams', 'Elvis Nolasco', 'Steven Hauck', 'Stephen Tyrone Williams']", 'Released_Year': '2014', 'Genre': "['Thriller', 'Comedy', 'Romance']"}, {'Rating': 8.0, 'Released_Year': '2005', 'Director': 'Frank Miller', 'Title': 'Sin City', 'Overview': 'A movie that explores the dark and miserable town, Basin City, tells the story of three different people, all caught up in violent corruption.', 'Genre': "['Crime', ' Thriller']", 'Cast': "['Quentin Tarantino', 'Robert Rodriguez', 'Mickey Rourke', 'Clive Owen']"}, {'Director': 'Not Provided', 'Genre': "['Crime', 'Drama']", 'Cast': '[\'Robert Blake\', \'Scott Wilson\', \'John Forsythe\', \'Paul Stewart\', "Gerald S. O\'Loughlin"]', 'Overview': "A 1967 film based on Truman Capote's book of the same name. After a botched robbery results in the brutal murder of a rural family, two drifters elude police, in the end coming to terms with their own mortality and the repercussions of their vile atrocity.", 'Rating': 7.4, 'Title': 'In Cold Blood', 'Released_Year': '1967'}, {'Genre': "['Adventure', 'Action', 'Thriller']", 'Director': 'Not Provided', 'Title': 'Ong Bak 2', 'Overview': 'Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father.', 'Cast': "['Tony Jaa', 'Sorapong Chatree', 'Sarunyu Wongkrachang', 'Primorata Dejudom']", 'Rating': 6.0, 'Released_Year': '2008'}, {'Overview': 'An Asian assassin (Dong-gun Jang) is forced to hide in a small town in the American Badlands. Also starring Kate Bosworth, Danny Huston, Tony Cox and Academy Award winner Geoffrey Rush.', 'Title': "The Warrior's Way", 'Released_Year': '2010', 'Genre': "['Adventure', 'Fantasy', 'Action', 'Western', 'Thriller']", 'Rating': 6.3, 'Director': 'Not Provided', 'Cast': "['Kate Bosworth', 'Jang Dong-gun', 'Geoffrey Rush', 'Danny Huston', 'Ti Lung']"}]]), ('distances', [[0.9720831513404846, 0.9729076623916626, 1.0059107542037964, 1.0658190250396729, 1.0685348510742188, 1.0776920318603516, 1.0964066982269287, 1.1039066314697266, 1.104210615158081, 1.1059749126434326]])])

In [ ]:
ids= results["ids"][0]
documents = results["documents"][0]
metadatas = results["metadatas"][0]

In [ ]:
documents

["Redemption Road:A Tennessee-set drama focused on an individual's spiritual redemption. ",
 "Gangster's Paradise: Jerusalema:This South African movie tracks the rise of a once-petty criminal to the heights of the criminal underworld. After cutting his teeth on hijacking, before moving onto bigger game, an ambitious man hits a setback when most of his gang are shot. ",
 'The Shawshank Redemption:Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. ',
 'Love and Other Catastrophes:A day in the life of two film-school students trying to find love and another house-mate. ',
 'Pulp Fiction:The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption. ',
 'Da Sweet Blood of Jesus:A movie about human beings who are addicted to blood. ',
 'Sin City:A movie that explores the dark and miserable town, Basin City, tells the story of three different people, all caught up in violent corruption. ',
 "In Cold Blood:A 1967 film based on Truman Capote's book of the same name. After a botched robbery results in the brutal murder of a rural family, two drifters elude police, in the end coming to terms with their own mortality and the repercussions of their vile atrocity. ",
 'Ong Bak 2:Moments from death a young man is rescued by a renowned warrior. Realizing unsurpassed physical potential in the young boy he trains him into the most dangerous man alive. As he becomes a young man he goes on a lone mission of vengeance against the vicious slave traders who enslaved him as a youth and the treacherous warlord who killed his father. ',
 "The Warrior's Way:An Asian assassin (Dong-gun Jang) is forced to hide in a small town in the American Badlands. Also starring Kate Bosworth, Danny Huston, Tony Cox and Academy Award winner Geoffrey Rush. "]

In [ ]:
# Implementing Cache in Semantic Search

# Set a threshold for cache search
threshold = 0.2

ids = []
documents = []
distances = []
metadatas = []
results_df = pd.DataFrame()

# Check if the distance is greater than the threshold, if so, return results from the main collection
if cache_results['distances'][0] == [] or cache_results['distances'][0][0] > threshold:
    # Query the collection against the user query and return the results
    results = collection.query(
        query_texts=query,
        n_results=5
    )

    # Store the query in cache_collection as a document with respect to ChromaDB for future reference
    # Store retrieved text, ids, distances, and metadatas in cache_collection as metadatas, so they can be fetched easily if a query indeed matches to a query in cache
    Keys = []
    Values = []

    for key, val in results.items():
        if val is None:
            continue
        for i in range(len(val[0])):  # Iterate over the actual length of val
            Keys.append(str(key) + str(i))
            if len(val[0]) > i:  # Check if the current index exists in val
                Values.append(str(val[0][i]))

    cache_collection.add(
        documents=[query],
        ids=[query],
        metadatas=dict(zip(Keys, Values))
    )

    # Print message indicating the results are found in the main collection
    print("Not found in cache. Found in the main collection.")

    # Construct a DataFrame from the query results
    result_dict = {'Metadatas': results['metadatas'][0], 'Documents': results['documents'][0], 'Distances': results['distances'][0], "IDs": results["ids"][0]}
    results_df = pd.DataFrame.from_dict(result_dict)


# If the distance is less than the threshold, return results from the cache
elif cache_results['distances'][0][0] <= threshold and cache_results['ids']:
    cache_result_dict = cache_results['metadatas'][0][0]

    # Loop through each inner list and then through the dictionary
    for key, value in cache_result_dict.items():
        if 'ids' in key:
            ids.append(value)
        elif 'documents' in key:
            documents.append(value)
        elif 'distances' in key:
            distances.append(value)
        elif 'metadatas' in key:
            metadatas.append(value)

    # Print message indicating the results are found in the cache
    print("Found in cache!")

    # Create a DataFrame from the cached results
    results_df = pd.DataFrame({
        'IDs': ids,
        'Documents': documents,
        'Distances': distances,
        'Metadatas': metadatas
    })
else:
    # Print message indicating no valid results found in cache
    print("No valid results found in cache!")

Not found in cache. Found in the main collection.

In [ ]:
results_df.head()

,Metadatas,Documents,Distances,IDs
0,"{'Director': 'Not Provided', 'Overview': 'A Te...",Redemption Road:A Tennessee-set drama focused ...,0.972083,4831
1,{'Overview': 'This South African movie tracks ...,Gangster's Paradise: Jerusalema:This South Afr...,0.972908,4919
2,"{'Title': 'The Shawshank Redemption', 'Genre':...",The Shawshank Redemption:Two imprisoned men bo...,1.005911,0
3,"{'Title': 'Love and Other Catastrophes', 'Over...",Love and Other Catastrophes:A day in the life ...,1.065819,5421
4,"{'Title': 'Pulp Fiction', 'Overview': 'The liv...","Pulp Fiction:The lives of two mob hitmen, a bo...",1.068535,6

In [ ]:
from sentence_transformers import CrossEncoder, util

In [ ]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [ ]:

cross_inputs = [[query, response] for response in results_df['Documents']]
cross_rerank_scores = cross_encoder.predict(cross_inputs)

results_df['Reranked_scores'] = cross_rerank_scores

In [ ]:
results_df.head()

,Metadatas,Documents,Distances,IDs,Reranked_scores
0,"{'Director': 'Not Provided', 'Overview': 'A Te...",Redemption Road:A Tennessee-set drama focused ...,0.972083,4831,-5.905139
1,{'Overview': 'This South African movie tracks ...,Gangster's Paradise: Jerusalema:This South Afr...,0.972908,4919,-7.199008
2,"{'Title': 'The Shawshank Redemption', 'Genre':...",The Shawshank Redemption:Two imprisoned men bo...,1.005911,0,-1.841225
3,"{'Title': 'Love and Other Catastrophes', 'Over...",Love and Other Catastrophes:A day in the life ...,1.065819,5421,-10.931244
4,"{'Title': 'Pulp Fiction', 'Overview': 'The liv...","Pulp Fiction:The lives of two mob hitmen, a bo...",1.068535,6,-6.866312

In [ ]:
### Semantic

semantic = results_df.sort_values(by='Distances')
semantic[:3]

,Metadatas,Documents,Distances,IDs,Reranked_scores
0,"{'Director': 'Not Provided', 'Overview': 'A Te...",Redemption Road:A Tennessee-set drama focused ...,0.972083,4831,-5.905139
1,{'Overview': 'This South African movie tracks ...,Gangster's Paradise: Jerusalema:This South Afr...,0.972908,4919,-7.199008
2,"{'Title': 'The Shawshank Redemption', 'Genre':...",The Shawshank Redemption:Two imprisoned men bo...,1.005911,0,-1.841225

In [ ]:
rank = results_df.sort_values(by='Reranked_scores')
rank[:3]

,Metadatas,Documents,Distances,IDs,Reranked_scores
3,"{'Title': 'Love and Other Catastrophes', 'Over...",Love and Other Catastrophes:A day in the life ...,1.065819,5421,-10.931244
1,{'Overview': 'This South African movie tracks ...,Gangster's Paradise: Jerusalema:This South Afr...,0.972908,4919,-7.199008
4,"{'Title': 'Pulp Fiction', 'Overview': 'The liv...","Pulp Fiction:The lives of two mob hitmen, a bo...",1.068535,6,-6.866312

In [ ]:
final = rank[["Documents", "Metadatas", "IDs"]]

In [ ]:
final.to_csv("drive/MyDrive/MyntraDataset/final_dataset.csv", index=False)

In [ ]:
## RAG layer

In [ ]:
import openai