In [ ]:
import pandas as pd

In [ ]:
df_plot = pd.read_csv("/content/drive/MyDrive/data_movie/data_movie/plot_details.csv")

In [ ]:
df_plot.head()

,Release Year,Title,Plot
0,1901,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,The earliest known adaptation of the classic f...

In [ ]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [ ]:
!pip install chromadb

Collecting chromadb
  Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.4.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.42.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.80.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.1)
Collecting opentelemetry-exporter-otlp-proto-common==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.8.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.6)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 111.8 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 32.4 MB/s eta 0:00:00
Downloading build-1.4.2-py3-none-any.whl (24 kB)
Downloading kubernetes-35.0.0-py2.py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 109.1 MB/s eta 0:00:00
Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 125.4 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl (20 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 9.7 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 20.0 MB/s eta 0:00:00
Downloading opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 kB 8.7 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 29.1 MB/s eta 0:00:00
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 9.8 MB/s eta 0:00:00
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 8.6 MB/s eta 0:00:00
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pypika, durationpy, pyproject_hooks, pybase64, opentelemetry-proto, bcrypt, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, onnxruntime, build, opentelemetry-semantic-conventions, kubernetes, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:
      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.38.0
    Uninstalling opentelemetry-sdk-1.38.0:
      Successfully uninstalled opentelemetry-sdk-1.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
google-adk 1.28.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.40.0 which is incompatible.
google-adk 1.28.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
Successfully installed bcrypt-5.0.0 build-1.4.2 chromadb-1.5.5 durationpy-0.10 kubernetes-35.0.0 onnxruntime-1.24.4 opentelemetry-api-1.40.0 opentelemetry-exporter-otlp-proto-common-1.40.0 opentelemetry-exporter-otlp-proto-grpc-1.40.0 opentelemetry-proto-1.40.0 opentelemetry-sdk-1.40.0 opentelemetry-semantic-conventions-0.61b0 pybase64-1.4.3 pypika-0.51.1 pyproject_hooks-1.2.0

In [ ]:
from sentence_transformers import SentenceTransformer, util
from sentence_transformers import SentenceTransformer

### Initializing sentence embedding model
model_name = "all-MiniLM-L6-v2"
embedder = SentenceTransformer(model_name, device="cuda")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
import chromadb

chroma_db_path = '/content/drive/MyDrive/data_movie/data_movie/plotDB_2'

client = chromadb.PersistentClient(path=chroma_db_path)

In [ ]:
import re

def clean_text(desc):
  modified_text = desc.replace("<ul>", "").replace("</ul>", "").replace("<li>", "").replace("</li>", ",").replace("<br>", ".")
  final = re.sub(r'<[^>]*>', '', modified_text).replace(". .",".")
  return final

In [ ]:
df_plot["Plot"] = df_plot["Plot"].apply(clean_text)

In [ ]:
def truncate_text(text, max_words=200):
    return " ".join(text.split()[:max_words])

df_plot['short_plot'] = df_plot['Plot'].apply(truncate_text)

In [ ]:
df_plot["metadata"] = df_plot.apply(lambda x: {
    "Title": x["Title"],
    "Plot": x["Plot"],
    "Release_Year": x["Release Year"],
    "short_plot": x["short_plot"]
}, axis=1)

In [ ]:

def get_search_text(metadata):
  text = ""
  ### Adding product description
  text += metadata["short_plot"] + " "

  if len(text) == 0:
    text = "No available description"

  return text

In [ ]:
df_plot["text_search"] = df_plot["metadata"].apply(get_search_text)

In [ ]:
df_plot.head()

,Release Year,Title,Plot,short_plot,metadata,text_search
0,1901,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr...","A bartender is working at a saloon, serving dr...","{'Title': 'Kansas Saloon Smashers', 'Plot': 'A...","A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov...","The moon, painted with a smiling face hangs ov...","{'Title': 'Love by the Light of the Moon', 'Pl...","The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,"The film, just over a minute long, is composed...","The film, just over a minute long, is composed...","{'Title': 'The Martyred Presidents', 'Plot': '...","The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...,Lasting just 61 seconds and consisting of two ...,"{'Title': 'Terrible Teddy, the Grizzly King', ...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,The earliest known adaptation of the classic f...,The earliest known adaptation of the classic f...,"{'Title': 'Jack and the Beanstalk', 'Plot': 'T...",The earliest known adaptation of the classic f...

In [ ]:
len(df_plot)

34886

In [ ]:
df_plot= df_plot[df_plot["Release Year"]> 1950]

In [ ]:
len(df_plot)

28360

In [ ]:
def generate_embeddings(texts):
    embeddings = embedder.encode(texts, convert_to_tensor=False)
    return embeddings

In [ ]:
embeddings = embedder.encode(
    df_plot['short_plot'].tolist(),
    batch_size=128,
    show_progress_bar=True
)

Batches:   0%|          | 0/222 [00:00<?, ?it/s]

In [ ]:
df_plot["embeddings"] = embeddings.tolist()

In [ ]:
df_plot.to_csv("drive/MyDrive/data_movie/data_movie/movie_plot_mod.csv", index=False)

In [ ]:
collection = client.get_or_create_collection(name='Movie_plot')

In [ ]:
ids = [str(i) for i in range(len(df_plot))]

In [ ]:
max_batch_size = 5000  # safe margin

for i in range(0, len(df_plot), max_batch_size):
    batch = df_plot.iloc[i:i+max_batch_size]

    collection.add(
        embeddings=batch['embeddings'].tolist(),
        documents=batch['text_search'].tolist(),
        metadatas=batch['metadata'].tolist(),
        ids=ids[i:i+max_batch_size]
    )

In [ ]:
cache_collection_name = 'Cache'

In [ ]:
cache_collection = client.get_or_create_collection(name=cache_collection_name)

In [ ]:
import requests

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

def get_movie_plot(movie_name):
    base_url = "https://en.wikipedia.org/w/api.php"

    # Step 1: Search correct page
    search_params = {
        "action": "query",
        "list": "search",
        "srsearch": movie_name + " film",
        "format": "json"
    }

    res = requests.get(base_url, params=search_params, headers=HEADERS)
    data = res.json()

    results = data.get("query", {}).get("search", [])
    if not results:
        return "Movie not found"

    page_title = results[0]["title"]

    # Step 2: Get sections
    section_params = {
        "action": "parse",
        "page": page_title,
        "prop": "sections",
        "format": "json"
    }

    res = requests.get(base_url, params=section_params, headers=HEADERS)
    data = res.json()

    sections = data.get("parse", {}).get("sections", [])

    # Step 3: Find plot section index
    plot_index = None
    for sec in sections:
        title = sec["line"].lower()
        if any(k in title for k in ["plot", "synopsis", "premise"]):
            plot_index = sec["index"]
            break

    if not plot_index:
        return "Plot section not found"

    # Step 4: Fetch that section content
    content_params = {
        "action": "parse",
        "page": page_title,
        "prop": "text",
        "section": plot_index,
        "format": "json"
    }

    res = requests.get(base_url, params=content_params, headers=HEADERS)
    data = res.json()

    html = data["parse"]["text"]["*"]

    # Step 5: Clean HTML → text
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html, "html.parser")

    paragraphs = [p.get_text() for p in soup.find_all("p")]

    return "\n".join(paragraphs).strip()


# Test
print(get_movie_plot("Inception"))
print(get_movie_plot("Avatar"))
print(get_movie_plot("The Dark Knight"))

Dom Cobb and Arthur are "extractors" who perform corporate espionage using experimental dream-sharing technology to infiltrate their targets' subconscious and extract information. Their latest target, Saito, is impressed with Cobb's ability to layer multiple dreams within each other. He offers to hire Cobb for the ostensibly impossible job of implanting an idea into a person's subconscious; performing "inception" on Robert Fischer, the son of Saito's competitor Maurice Fischer, with the idea to dissolve his father's company. In return, Saito promises to clear Cobb's criminal status, allowing him to return home to his children.

Cobb accepts the offer and assembles his team: a forger named Eames, a chemist named Yusuf, and a college student named Ariadne. Ariadne is tasked with designing the dream's architecture, something Cobb himself cannot do for fear of being sabotaged by his mind's projection of his late wife, Mal. Maurice Fischer dies, and the team sedates Robert Fischer into a three-layer shared dream on an airplane to America bought by Saito. Time on each layer runs slower than the layer above, with one member staying behind on each to perform a music-synchronized "kick" (using the French song "Non, je ne regrette rien") to awaken dreamers on all three levels simultaneously.

The team abducts Robert in a city on the first level, but unknown to any team member, his subconscious projections, trained to anticipate such a scenario, attack them. After Saito is wounded, Cobb reveals that while dying in the dream would usually awaken dreamers, Yusuf's sedatives will instead send them into "Limbo": a world of infinite subconscious. Eames impersonates Robert's godfather, Peter Browning, to introduce the idea of an alternate will to dissolve the company.

Cobb explains to Ariadne that he and Mal entered Limbo while experimenting with dream-sharing, experiencing fifty years in one night due to the time dilation with reality. After waking up, Mal still believed she was dreaming. Attempting to "wake up," she committed suicide and framed Cobb for her murder to force him to do the same. Cobb fled the U.S., leaving his children behind.

Yusuf drives the team around the first level as they are sedated into the second level, a hotel dreamed by Arthur. Cobb persuades Robert that Browning has kidnapped him to stop the dissolution and that Cobb is a defensive projection, leading Robert to another third level deeper as part of a ruse to enter Robert's subconscious.

In the third level, the team infiltrates an alpine fortress with a projection of Maurice inside, where the inception itself can be performed. However, Yusuf performs his kick too soon by driving off a bridge, forcing Arthur and Eames to improvise a new set of kicks synchronized with them hitting the water by rigging an elevator and the fortress, respectively, with explosives. Mal then appears and kills Robert before he can be subjected to the inception; he and Saito are subsequently lost in Limbo, forcing Cobb and Ariadne to rescue them in time for Robert's inception and Eames's kick. Cobb reveals that during their time in Limbo, Mal refused to return to reality; Cobb had to convince her it was only a dream, accidentally incepting in her the belief that the real world was still a dream. Cobb makes peace with his part in Mal's death. Ariadne kills Mal's projection and wakes Robert up with a kick.

Revived into the third level, Robert discovers the planted idea: his dying father telling him to create something for himself. While Cobb searches for Saito in Limbo, the others ride the synced kicks back to reality. Cobb finds an aged Saito and reminds him of their agreement. The dreamers all awaken on the plane, and Saito makes a phone call. Arriving in Los Angeles, Cobb passes the immigration checkpoint, and his father-in-law accompanies him to his home. Cobb uses Mal's "totem" – a top that spins indefinitely in a dream – to test if he is indeed in the real world, but he chooses not to observe the result and instead joins his children.
In 2154, Earth suffers from resource exhaustion and ecological collapse. The Resources Development Administration (RDA) mines the valuable mineral unobtanium on Pandora, a lush habitable moon in the Alpha Centauri star system. Pandora is inhabited by the Na'vi, a 10-foot-tall (3.0 m), blue-skinned, sapient humanoid species that live in harmony with nature.

To explore Pandora, human scientists control Na'vi-human hybrid bodies called "avatars". Each avatar is genetically matched with a human operator. Jake Sully, a paraplegic veteran of the United States Marines, is recruited as an operator after the death of his identical twin, who was training as an operator. The head of the Avatar Program, Dr. Grace Augustine, allows Jake to take the place of his twin, but considers him inadequate.

While Jake, Grace and Dr. Norm Spellman are in their avatars in the forest, Jake is attacked by wild animals. He flees deep into the wilderness, where he is rescued by a female Na'vi named Neytiri. Suspicious of Jake, she takes him to her clan, the Omaticaya. Mo'at, the clan's spiritual leader and the mother of Neytiri, orders her daughter to initiate Jake into their society.

Colonel Miles Quaritch, head of the RDA's security force, promises Jake that the company will restore the use of his legs if he provides information about the Na'vi and their gathering place, the giant Hometree, which sits atop a rich deposit of unobtanium. Jake and Neytiri fall in love as Jake is initiated into the clan, and they choose each other as mates. When Jake attempts to disable a bulldozer threatening a sacred Na'vi site, RDA administrator Parker Selfridge orders the destruction of Hometree.

Grace explains to Selfridge that destroying Hometree would damage the biological neural network that connects all Pandoran life, which prompts Selfridge to reluctantly give Jake and Grace one hour to convince the Na'vi to evacuate. Jake confesses to the Na'vi that he was a spy for the RDA, which prompts the clan to take him and Grace captive. Quaritch's soldiers destroy Hometree and kill many Na'vi, including Eytukan, who is the clan chief and Neytiri's father. Mo'at frees Jake and Grace, but they are detached from their avatars and imprisoned by Quaritch's forces. Trudy Chacón, a pilot who is disgusted by Quaritch's brutality, rescues Jake, Grace, and Norm. During the escape, Grace is shot and fatally wounded.

Jake regains the trust of the Na'vi by connecting his mind to the Toruk, a dragon-like creature feared and revered by the clan. Supported by Neytiri and the new chief Tsu'tey, Jake unites the Omaticaya, and tells them to gather other Na'vi clans to fight the RDA as it prepares to assault the Tree of Souls. Before the battle, Jake prays to the Na'vi mother goddess Eywa through a neural connection with the Tree of Souls.

The Na'vi and their human allies lose many fighters during the battle, including Tsu'tey and Trudy. The tide turns when wild animals unexpectedly join the fight and overwhelm the RDA forces; Neytiri interprets this occurrence as Eywa answering Jake's prayer. Quaritch, in an Amplified Mobility Platform suit, breaks open the avatar link unit containing Jake's human body, exposing it to Pandora's poisonous atmosphere. As Quaritch prepares to kill Jake, he is slain by Neytiri, who then saves Jake from suffocation.

In the aftermath of the war, the RDA is expelled from Pandora. Some humans are allowed to remain, including Jake and Norm. With the help of the Tree of Souls, Neytiri, and Mo'at, Jake is permanently transferred into his avatar.
A gang of masked criminals rob a mafia-owned bank in Gotham City, betraying and killing each other until the sole survivor, the Joker, reveals himself as the mastermind and escapes with the money. The vigilante Batman, district attorney Harvey Dent, and police lieutenant Jim Gordon ally to eliminate Gotham's organized crime. Batman's true identity, the billionaire Bruce Wayne, publicly supports Dent as Gotham's legitimate protector, believing Dent's success will allow him to retire as Batman and romantically pursue his childhood friend Rachel Dawes—despite her being with Dent.

Gotham's mafia bosses gather to discuss protecting their organizations from the Joker, the police, and Batman. The Joker interrupts the meeting and offers to kill Batman for half of the fortune their accountant, Lau, concealed before fleeing to Hong Kong to avoid extradition. With the help of Wayne Enterprises CEO Lucius Fox, Batman finds Lau in Hong Kong and returns him to the custody of the Gotham police. His testimony enables Dent to apprehend the crime families. The bosses accept the Joker's offer, and he kills high-profile targets involved in the trial, including the judge and police commissioner. Although Gordon saves the mayor, the Joker threatens that his attacks will continue until Batman reveals his identity. He targets Dent at a fundraising dinner and throws Rachel out of a window, but Batman rescues her.

Bruce struggles to understand the Joker's motives, to which his butler Alfred Pennyworth says that "some men just want to watch the world burn." Dent claims he is Batman to lure the Joker out, who attacks the police convoy transporting Dent. Batman and Gordon apprehend the Joker, and Gordon is promoted to commissioner. At the police station, Batman interrogates the Joker, who says he finds Batman entertaining and has no intention of killing him. Having deduced Batman's feelings for Rachel, the Joker reveals she and Dent are being held separately in buildings rigged to explode. Batman races to rescue Rachel while Gordon and the other officers go after Dent, but they discover the Joker has given their positions in reverse. The explosives detonate, killing Rachel and severely burning Dent's face on one side. The Joker escapes custody, extracts the fortune's location from Lau, and burns it, killing Lau in the process.

Coleman Reese, a consultant for Wayne Enterprises, deduces and tries to expose Batman's identity, but the Joker threatens to blow up a hospital unless Reese is killed. While the police evacuate hospitals and Gordon struggles to keep Reese alive, the Joker meets with a disillusioned Dent, persuading him to take the law into his own hands and avenge Rachel. Dent defers his decision-making to his now half-scarred, two-headed coin, killing the corrupt officers and the mafia involved in Rachel's death. As panic grips the city, the Joker reveals that two evacuation ferries, one carrying civilians and the other prisoners, are rigged to explode at midnight unless one group sacrifices the other. To the Joker's disbelief, the passengers refuse to kill one another. Batman subdues the Joker but refuses to kill him. Before the police arrest the Joker, he says that although Batman proved incorruptible, his plan to corrupt Dent has succeeded.

Dent takes Gordon's family hostage, blaming his negligence for Rachel's death. He flips his coin to decide their fates, but Batman tackles him to save Gordon's son, and Dent falls to his death. Believing Dent is the hero the city needs, and the truth of his corruption will harm Gotham, Batman takes the blame for his death and actions, persuading Gordon to conceal the truth. Alfred burns an undelivered letter from Rachel to Bruce that says she chose Dent, and Fox destroys the invasive surveillance network that helped Batman find the Joker. The city mourns Dent as a hero, and the police launch a manhunt for Batman.

In [ ]:
movie_target = get_movie_plot("Inception")

In [ ]:
movie_target

'Dom Cobb and Arthur are "extractors" who perform corporate espionage using experimental dream-sharing technology to infiltrate their targets\' subconscious and extract information. Their latest target, Saito, is impressed with Cobb\'s ability to layer multiple dreams within each other. He offers to hire Cobb for the ostensibly impossible job of implanting an idea into a person\'s subconscious; performing "inception" on Robert Fischer, the son of Saito\'s competitor Maurice Fischer, with the idea to dissolve his father\'s company. In return, Saito promises to clear Cobb\'s criminal status, allowing him to return home to his children.\n\nCobb accepts the offer and assembles his team: a forger named Eames, a chemist named Yusuf, and a college student named Ariadne. Ariadne is tasked with designing the dream\'s architecture, something Cobb himself cannot do for fear of being sabotaged by his mind\'s projection of his late wife, Mal. Maurice Fischer dies, and the team sedates Robert Fischer into a three-layer shared dream on an airplane to America bought by Saito. Time on each layer runs slower than the layer above, with one member staying behind on each to perform a music-synchronized "kick" (using the French song "Non, je ne regrette rien") to awaken dreamers on all three levels simultaneously.\n\nThe team abducts Robert in a city on the first level, but unknown to any team member, his subconscious projections, trained to anticipate such a scenario, attack them. After Saito is wounded, Cobb reveals that while dying in the dream would usually awaken dreamers, Yusuf\'s sedatives will instead send them into "Limbo": a world of infinite subconscious. Eames impersonates Robert\'s godfather, Peter Browning, to introduce the idea of an alternate will to dissolve the company.\n\nCobb explains to Ariadne that he and Mal entered Limbo while experimenting with dream-sharing, experiencing fifty years in one night due to the time dilation with reality. After waking up, Mal still believed she was dreaming. Attempting to "wake up," she committed suicide and framed Cobb for her murder to force him to do the same. Cobb fled the U.S., leaving his children behind.\n\nYusuf drives the team around the first level as they are sedated into the second level, a hotel dreamed by Arthur. Cobb persuades Robert that Browning has kidnapped him to stop the dissolution and that Cobb is a defensive projection, leading Robert to another third level deeper as part of a ruse to enter Robert\'s subconscious.\n\nIn the third level, the team infiltrates an alpine fortress with a projection of Maurice inside, where the inception itself can be performed. However, Yusuf performs his kick too soon by driving off a bridge, forcing Arthur and Eames to improvise a new set of kicks synchronized with them hitting the water by rigging an elevator and the fortress, respectively, with explosives. Mal then appears and kills Robert before he can be subjected to the inception; he and Saito are subsequently lost in Limbo, forcing Cobb and Ariadne to rescue them in time for Robert\'s inception and Eames\'s kick. Cobb reveals that during their time in Limbo, Mal refused to return to reality; Cobb had to convince her it was only a dream, accidentally incepting in her the belief that the real world was still a dream. Cobb makes peace with his part in Mal\'s death. Ariadne kills Mal\'s projection and wakes Robert up with a kick.\n\nRevived into the third level, Robert discovers the planted idea: his dying father telling him to create something for himself. While Cobb searches for Saito in Limbo, the others ride the synced kicks back to reality. Cobb finds an aged Saito and reminds him of their agreement. The dreamers all awaken on the plane, and Saito makes a phone call. Arriving in Los Angeles, Cobb passes the immigration checkpoint, and his father-in-law accompanies him to his home. Cobb uses Mal\'s "totem" – a top that spins indefinitely in a dream – to test if he is indeed in the real world, but he chooses not to observe the result and instead joins his children.'

In [ ]:
cleaned_text = clean_text(movie_target)

In [ ]:
cleaned_text

'Dom Cobb and Arthur are "extractors" who perform corporate espionage using experimental dream-sharing technology to infiltrate their targets\' subconscious and extract information. Their latest target, Saito, is impressed with Cobb\'s ability to layer multiple dreams within each other. He offers to hire Cobb for the ostensibly impossible job of implanting an idea into a person\'s subconscious; performing "inception" on Robert Fischer, the son of Saito\'s competitor Maurice Fischer, with the idea to dissolve his father\'s company. In return, Saito promises to clear Cobb\'s criminal status, allowing him to return home to his children.\n\nCobb accepts the offer and assembles his team: a forger named Eames, a chemist named Yusuf, and a college student named Ariadne. Ariadne is tasked with designing the dream\'s architecture, something Cobb himself cannot do for fear of being sabotaged by his mind\'s projection of his late wife, Mal. Maurice Fischer dies, and the team sedates Robert Fischer into a three-layer shared dream on an airplane to America bought by Saito. Time on each layer runs slower than the layer above, with one member staying behind on each to perform a music-synchronized "kick" (using the French song "Non, je ne regrette rien") to awaken dreamers on all three levels simultaneously.\n\nThe team abducts Robert in a city on the first level, but unknown to any team member, his subconscious projections, trained to anticipate such a scenario, attack them. After Saito is wounded, Cobb reveals that while dying in the dream would usually awaken dreamers, Yusuf\'s sedatives will instead send them into "Limbo": a world of infinite subconscious. Eames impersonates Robert\'s godfather, Peter Browning, to introduce the idea of an alternate will to dissolve the company.\n\nCobb explains to Ariadne that he and Mal entered Limbo while experimenting with dream-sharing, experiencing fifty years in one night due to the time dilation with reality. After waking up, Mal still believed she was dreaming. Attempting to "wake up," she committed suicide and framed Cobb for her murder to force him to do the same. Cobb fled the U.S., leaving his children behind.\n\nYusuf drives the team around the first level as they are sedated into the second level, a hotel dreamed by Arthur. Cobb persuades Robert that Browning has kidnapped him to stop the dissolution and that Cobb is a defensive projection, leading Robert to another third level deeper as part of a ruse to enter Robert\'s subconscious.\n\nIn the third level, the team infiltrates an alpine fortress with a projection of Maurice inside, where the inception itself can be performed. However, Yusuf performs his kick too soon by driving off a bridge, forcing Arthur and Eames to improvise a new set of kicks synchronized with them hitting the water by rigging an elevator and the fortress, respectively, with explosives. Mal then appears and kills Robert before he can be subjected to the inception; he and Saito are subsequently lost in Limbo, forcing Cobb and Ariadne to rescue them in time for Robert\'s inception and Eames\'s kick. Cobb reveals that during their time in Limbo, Mal refused to return to reality; Cobb had to convince her it was only a dream, accidentally incepting in her the belief that the real world was still a dream. Cobb makes peace with his part in Mal\'s death. Ariadne kills Mal\'s projection and wakes Robert up with a kick.\n\nRevived into the third level, Robert discovers the planted idea: his dying father telling him to create something for himself. While Cobb searches for Saito in Limbo, the others ride the synced kicks back to reality. Cobb finds an aged Saito and reminds him of their agreement. The dreamers all awaken on the plane, and Saito makes a phone call. Arriving in Los Angeles, Cobb passes the immigration checkpoint, and his father-in-law accompanies him to his home. Cobb uses Mal\'s "totem" – a top that spins indefinitely in a dream – to test if he is indeed in the real world, but he chooses not to observe the result and instead joins his children.'

In [ ]:
short_plot = truncate_text(cleaned_text)

In [ ]:
short_plot

'Dom Cobb and Arthur are "extractors" who perform corporate espionage using experimental dream-sharing technology to infiltrate their targets\' subconscious and extract information. Their latest target, Saito, is impressed with Cobb\'s ability to layer multiple dreams within each other. He offers to hire Cobb for the ostensibly impossible job of implanting an idea into a person\'s subconscious; performing "inception" on Robert Fischer, the son of Saito\'s competitor Maurice Fischer, with the idea to dissolve his father\'s company. In return, Saito promises to clear Cobb\'s criminal status, allowing him to return home to his children. Cobb accepts the offer and assembles his team: a forger named Eames, a chemist named Yusuf, and a college student named Ariadne. Ariadne is tasked with designing the dream\'s architecture, something Cobb himself cannot do for fear of being sabotaged by his mind\'s projection of his late wife, Mal. Maurice Fischer dies, and the team sedates Robert Fischer into a three-layer shared dream on an airplane to America bought by Saito. Time on each layer runs slower than the layer above, with one member staying behind on each to perform a music-synchronized "kick" (using the French song "Non, je ne regrette rien") to awaken dreamers on all'

In [ ]:
query = f"""

Find movie plots similar to:

{short_plot}

"""

In [ ]:
### Getting first 10 matches

results = collection.query(
query_texts=query,
n_results=10
)
results.items()

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:01<00:00, 43.8MiB/s]

dict_items([('ids', [['10570', '14486', '21094', '15871', '9932', '11998', '5263', '11643', '24823', '15830']]), ('embeddings', None), ('documents', [['Dominick "Dom" Cobb and Arthur are "extractors", who perform corporate espionage using an experimental military technology to infiltrate the subconscious of their targets and extract valuable information through a shared dream world. Their latest target, Japanese businessman Saito, reveals that he arranged their mission himself to test Cobb for a seemingly impossible job: planting an idea in a person\'s subconscious, or "inception". To break up the energy conglomerate of ailing competitor Maurice Fischer, Saito wants Cobb to convince Fischer\'s son and heir, Robert, to dissolve his father\'s company. In return, Saito promises to use his influence to clear Cobb of a murder charge, allowing Cobb to return home to his children. Cobb accepts the offer and assembles his team: Eames, a conman and identity forger; Yusuf, a chemist who concocts a powerful sedative for a stable "dream within a dream" strategy; and Ariadne, an architecture student tasked with designing the labyrinth of the dream landscapes, recruited with the help of Cobb\'s father-in-law, Professor Stephen Miles. While dream-sharing with Cobb, Ariadne learns his subconscious houses an invasive projection of his late wife Mal. When the elder Fischer dies in Sydney, Robert Fischer accompanies the body on a ten-hour flight back to ', 'The plot is non-linear, and the end scene of the film shows the real beginning of the story.[7] There are two main roles, one that is played out in the dream, and the other one in reality, called respectively Nikhil and Nikki.[7] The plot starts with the protagonist being in a state of coma and continuing only on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white.[8] Sanjay, a detective from the Mumbai police Crime Branch starts investigating the incident that caused the protagonist\'s (Sathish Ninasam) current state. While Sanjay is going through the protagonist\'s belongings he stumbles upon some scribbled notes and a mysterious pill. Meanwhile, the police capture two suspects and interrogate them. The story starts with Nikki in a village near Mandya, working as an usher/"torch-shiner" in a Bengaluru movie theatre owned by Shankranna (Achyuth Kumar). Nikki has insomnia and yearns for a companion. On one of his sleepless nights Nikki is contacted by a drug dealer who gives him Lucia pills as a solution to his sleeping problems. This drug is said to have the capacity to help one dream the ', 'The plot is non-linear, and the end scene of the film shows the real beginning of the story.[7] There are two main roles, one that is played out in the dream, and the other one in reality, called respectively Nikhil and Nikki.[7] The plot starts with the protagonist being in a state of coma and continuing only on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white.[8] Sanjay, a detective from the Mumbai police Crime Branch starts investigating the incident that caused the protagonist\'s (Sathish Ninasam) current state. While Sanjay is going through the protagonist\'s belongings he stumbles upon some scribbled notes and a mysterious pill. Meanwhile, the police capture two suspects and interrogate them. The story starts with Nikki in a village near Mandya, working as an usher/"torch-shiner" in a Bengaluru movie theatre owned by Shankranna (Achyuth Kumar). Nikki has insomnia and yearns for a companion. On one of his sleepless nights Nikki is contacted by a drug dealer who gives him Lucia pills as a solution to his sleeping problems. This drug is said to have the capacity to help one dream the ', 'The film starts with a man, Ryjkin, trying to escape from the Cube. He enters a room and is sprayed with liquid that he thinks is only water. However, when he rubs the back of his hand due to itchiness, his flesh liquifies and falls off. This soon happens all over his body, as he then melts on the floor and dies as a result. A man named Eric is watching a video feed of this in an observation room with a co-worker named Dodd. Afterwards, Eric is shown to be sketching a portrait of Dodd in the form of a superhero called Chessman, while playing chess with him at the same time. Dodd has the chess board in front of him, but Eric is at another table, simply drawing and naming his moves. Eric seems to be vastly intelligent, calculating all of Dodd\'s moves. After Eric wins, he asks Dodd questions about their missing colleagues. Dodd tells him not to ask too many questions or get involved with the occupants of the Cube because it wouldn\'t make "those upstairs" happy. Both Eric and Dodd get an order from "upstairs" that asks them to record the dream of a subject, ', 'The movie follows a man\'s search for perfection in a world where life rarely measures up to the idealized images that constantly bombard us. Gary Shaller (Freeman), who gained commercial success in previous years as the keyboard player in the fictional band "On The One". He is in a failing marriage with Dora (Gwyneth Paltrow), and working for his former band mate Paul (Simon Pegg), writing and recording commercial jingles. Gary eventually discovers that he is having lucid dreams about a glamorous woman named Anna (Penélope Cruz), with whom he is deeply infatuated. He aims to learn more about lucid dreaming by buying books and even attending classes taught by an eccentric lucid-dreaming enthusiast, Mel (Danny DeVito). Gary eventually discovers that the girl he dreams about does, in fact, exist. Paul arranges for Gary to meet her, but this proves disappointing, as she fails to live up to the expectations that Gary has built up in his dreams of her. He eventually continues to dream about her, and even soundproofs his apartment, and makes other efforts to be able to sleep longer, so that he can remain with Anna for longer periods of time. Eventually, feeling as though he is ', 'Eleven-year-old Jake Chambers experiences visions involving a Man in Black who seeks to destroy a Tower and bring ruin to the Universe, and a Gunslinger who opposes him. Jake\'s mother, stepfather, and psychiatrists dismiss these as dreams resulting from the trauma of his father’s death the previous year. At his apartment home in New York City, a group of workers from an alleged psychiatric facility offer to rehabilitate Jake; recognizing them from his visions as monsters wearing human skin, he flees. Jake tracks down an abandoned house from one of his visions, discovers a high-tech portal, and travels to a post-apocalyptic world called Mid-World. In Mid-World, Jake encounters the last Gunslinger, Roland Deschain who emerged in his visions. Roland is pursuing Walter Padick, the Man in Black, who had also appeared in Jake’s dreams, across a desert, seeking to kill him in revenge for the murder of his father, Steven, and all remaining gunslingers. He explains that Walter, over the decades, has been abducting psychic children, and is attempting to use their "shine" to bring down the Dark Tower, a fabled structure located at the center of the Universe; this will allow beings from the darkness outside to invade and ', "Author Roger Cobb is a troubled man, having been separated from his wife; their only son Jimmy disappeared without a trace and his aunt committed suicide by hanging. On top of everything else, he has been pressured by his publisher to write another book. To the chagrin of his fans and publisher, Cobb plans a novel based on his experiences in Vietnam, instead of another horror story, as a way to purge himself of the horrors that he had experienced while there. After his aunt's funeral, Cobb decides to live inside her house to write instead of selling it, as recommended by the estate attorney. After moving in, Cobb begins to have powerful graphic nightmares, including thoughts about his comrade, Big Ben, who died in Vietnam. In addition, strange phenomena spring forth from the house, haunting him in his waking hours. He tries communicating his fears to his next door neighbor Harold, but he thinks that Cobb is crazy. One night while investigating a noise coming from his late aunt's bedroom, Cobb is attacked by a deformed monster inside the closet. Soon, more attacks occur: levitating garden tools attack him, his wife appears and transforms into a hideous hag-like creature ", 'In 2014, 17-year-old high school senior and aspiring inventor David Raskin (Jonny Weston) is admitted into MIT, but is unable to afford its tuition fees. Upon learning his mother, Kathy Raskin (Amy Landecker), is planning to sell the house to help pay for his college, David enlists his sister Christina (Virginia Gardner) and his friends Adam Le (Allen Evangelista) and Quinn Goldberg (Sam Lerner) to sift through the belongings of his father Ben Raskin (Gary Weeks), an inventor who died in a car crash on David\'s seventh birthday, in the hope of finding something that David can use to get a scholarship instead. David finds an old camera with a video recording of his seventh birthday party, in which he briefly spots his 17-year-old self in a reflection. Noticing how he appears to be reaching for a basement light switch in the reflection, David and his friends go to the basement, which was forbidden by his father. Underneath a trapdoor activated by the basement switch, the group find the blueprints of a temporal relocation device that Ben was developing named "Project Almanac", and use the available resources to build a functional time machine. David, Christina, Adam, and Quinn later use ', 'The plot is non-linear, starting by showing the final scene of the film. The plot starts with the protagonist being in a state of coma and living on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white. A detective from Mumbai crime branch starts investigating the incident that caused the protagonist\'s (Siddharth) current state. The Detective going through his belongings stumbles upon some scribbled notes and a mysterious pill. Meanwhile, police capture two suspects and interrogate them for information. The story starts with Vicky who is from a village and working as an Usher/"torch-shiner" in a movie theatre owned by Durai (Aadukalam Naren). Vicky suffers from insomnia. On one of his sleepless nights Vicky is contacted by a drug dealer who gives him Lucia pills as a solution to his sleeping problems. This drug is said to have the capability to help one dream the life they want but has the side-effect, that on discontinuation the same dreams shall turn into a nightmare. With the help of the Lucia pills, Vicky starts seeing himself as being a successful actor called Vignesh surrounded by people he ', 'The film starts with a young woman named Becky (Greer Kent), shown to be trapped in the Cube. She enters another room, but unknown to her, the room has reversed gravity, as she is pulled up, and it is implied that she is killed. Some time later, a woman named Kate (Kari Matchett), detective Simon (Geraint Wyn Davies), a blind girl named Sasha (Grace Lynn Kung), engineer Jerry (Neil Crone), game developer Max (Matthew Ferguson), lawyer Julia (Lindsey Connell), and an elderly woman named Mrs. Paley (Barbara Gordon) find themselves trapped in brightly lit cubes, each with a panel on each of the six sides, which are doors to other rooms. They come across Colonel Thomas Maguire (Bruce Gray), who says that they have to solve the code in order to leave the mysterious place. Just as he finishes, a wall begins to close in on the group. The group escapes while Thomas stays behind, while Kate and Simon watch in horror as Thomas is disintegrated by the wall. Later experiences around the cube reveal that gravity can operate in different directions in each room, while Mrs. Paley, who is revealed to be a retired theoretical mathematician, and Jerry, realize ']]), ('uris', None), ('included', ['metadatas', 'documents', 'distances']), ('data', None), ('metadatas', [[{'short_plot': 'Dominick "Dom" Cobb and Arthur are "extractors", who perform corporate espionage using an experimental military technology to infiltrate the subconscious of their targets and extract valuable information through a shared dream world. Their latest target, Japanese businessman Saito, reveals that he arranged their mission himself to test Cobb for a seemingly impossible job: planting an idea in a person\'s subconscious, or "inception". To break up the energy conglomerate of ailing competitor Maurice Fischer, Saito wants Cobb to convince Fischer\'s son and heir, Robert, to dissolve his father\'s company. In return, Saito promises to use his influence to clear Cobb of a murder charge, allowing Cobb to return home to his children. Cobb accepts the offer and assembles his team: Eames, a conman and identity forger; Yusuf, a chemist who concocts a powerful sedative for a stable "dream within a dream" strategy; and Ariadne, an architecture student tasked with designing the labyrinth of the dream landscapes, recruited with the help of Cobb\'s father-in-law, Professor Stephen Miles. While dream-sharing with Cobb, Ariadne learns his subconscious houses an invasive projection of his late wife Mal. When the elder Fischer dies in Sydney, Robert Fischer accompanies the body on a ten-hour flight back to', 'Title': 'Inception', 'Plot': 'Dominick "Dom" Cobb and Arthur are "extractors", who perform corporate espionage using an experimental military technology to infiltrate the subconscious of their targets and extract valuable information through a shared dream world. Their latest target, Japanese businessman Saito, reveals that he arranged their mission himself to test Cobb for a seemingly impossible job: planting an idea in a person\'s subconscious, or "inception". To break up the energy conglomerate of ailing competitor Maurice Fischer, Saito wants Cobb to convince Fischer\'s son and heir, Robert, to dissolve his father\'s company. In return, Saito promises to use his influence to clear Cobb of a murder charge, allowing Cobb to return home to his children. Cobb accepts the offer and assembles his team: Eames, a conman and identity forger; Yusuf, a chemist who concocts a powerful sedative for a stable "dream within a dream" strategy; and Ariadne, an architecture student tasked with designing the labyrinth of the dream landscapes, recruited with the help of Cobb\'s father-in-law, Professor Stephen Miles. While dream-sharing with Cobb, Ariadne learns his subconscious houses an invasive projection of his late wife Mal.\r\nWhen the elder Fischer dies in Sydney, Robert Fischer accompanies the body on a ten-hour flight back to Los Angeles, which the team (including Saito, who wants to verify their success) uses as an opportunity to sedate and take Fischer into a shared dream. At each dream level, the person generating the dream stays behind to set up a "kick" that will be used to awaken the other sleeping team members from the deeper dream level; to be successful, these kicks must occur simultaneously at each dream level, a fact complicated due to the nature of time which flows much faster in each successive level. The first level is Yusuf\'s dream of a rainy Los Angeles. The team abducts Fischer, but they are attacked by armed projections from Fischer\'s subconscious, which has been specifically trained to defend him against such intruders. The team takes Fischer and a wounded Saito to a warehouse, where Cobb reveals that while dying in the dream would normally wake Saito up, the powerful sedatives needed to stabilize the multi-level dream will instead send a dying dreamer into "limbo", a world of infinite subconscious from which escape is extremely difficult, if not impossible, and a dreamer risks forgetting they are in a dream. Despite these setbacks, the team continues with the mission.\r\nEames impersonates Fischer\'s godfather, Peter Browning, to suggest Fischer reconsider his father\'s will. Yusuf drives the van as the other dreamers are sedated into the second level. In the second level, a hotel dreamed by Arthur, Cobb persuades Fischer that he has been kidnapped by Browning and Cobb is his subconscious protector. Cobb persuades him to go down another level to explore Browning\'s subconscious (in reality, it is a ruse to enter Fischer\'s). The third level is a fortified hospital on a snowy mountain dreamed by Eames. The team has to infiltrate it and hold off the guards as Cobb takes Fischer into the equivalent of his subconscious. Yusuf, under pursuit by Fischer\'s projections in the first level, deliberately drives off a bridge and initiates his kick too soon. This causes an avalanche in Eames\' level and removes the gravity of Arthur\'s level, forcing him to improvise a new kick synchronized with the van hitting the water. Mal\'s projection emerges and kills Fischer; Cobb kills Mal, and Saito succumbs to his wounds. Cobb and Ariadne enter Limbo to rescue Fischer and Saito, while Eames sets up a kick by rigging the hospital with explosives.\r\nCobb reveals to Ariadne that he and Mal went to Limbo while experimenting with the dream-sharing technology. Sedated for a few hours of real time, they spent fifty years in a dream constructing a world from their shared memories. When Mal refused to return to reality, Cobb used a rudimentary form of inception by reactivating her totem (an object dreamers use to distinguish dreams from reality) and reminding her subconscious that their world was not real. However, when she woke up, Mal still believed that she was dreaming. In an attempt to "wake up" for real, Mal committed suicide and framed Cobb for her death to force him to do the same. Facing a murder charge, Cobb fled the U.S., leaving his children in the care of Professor Miles.\r\nThrough his confession, Cobb makes peace with his guilt over Mal\'s death. Ariadne kills Mal\'s projection and wakes Fischer up with a kick. Revived at the mountain fort, Fischer enters a safe room to discover and accept the planted idea: a projection of his dying father telling him to be his own man. While Cobb remains in Limbo to search for Saito, the other team members ride the synchronized kicks back to reality. Cobb eventually finds an aged Saito in Limbo and reminds him of their agreement. The dreamers all awake on the plane and Saito makes a phone call.\r\nUpon arrival at Los Angeles Airport, Cobb passes the U.S. immigration checkpoint and Professor Miles accompanies him to his home. Using his totem—a spinning top that spins indefinitely in a dream world but falls over in reality—Cobb conducts a test to prove that he is indeed in the real world, but he ignores its result and instead joins his children in the garden.', 'Release_Year': 2010}, {'Release_Year': 1998, 'Title': 'Lucia', 'Plot': 'The plot is non-linear, and the end scene of the film shows the real beginning of the story.[7] There are two main roles, one that is played out in the dream, and the other one in reality, called respectively Nikhil and Nikki.[7] The plot starts with the protagonist being in a state of coma and continuing only on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white.[8]\r\nSanjay, a detective from the Mumbai police Crime Branch starts investigating the incident that caused the protagonist\'s (Sathish Ninasam) current state. While Sanjay is going through the protagonist\'s belongings he stumbles upon some scribbled notes and a mysterious pill. Meanwhile, the police capture two suspects and interrogate them.\r\nThe story starts with Nikki in a village near Mandya, working as an usher/"torch-shiner" in a Bengaluru movie theatre owned by Shankranna (Achyuth Kumar). Nikki has insomnia and yearns for a companion. O

In [ ]:
results

{'ids': [['10570',
   '14486',
   '21094',
   '15871',
   '9932',
   '11998',
   '5263',
   '11643',
   '24823',
   '15830']],
 'embeddings': None,
 'documents': [['Dominick "Dom" Cobb and Arthur are "extractors", who perform corporate espionage using an experimental military technology to infiltrate the subconscious of their targets and extract valuable information through a shared dream world. Their latest target, Japanese businessman Saito, reveals that he arranged their mission himself to test Cobb for a seemingly impossible job: planting an idea in a person\'s subconscious, or "inception". To break up the energy conglomerate of ailing competitor Maurice Fischer, Saito wants Cobb to convince Fischer\'s son and heir, Robert, to dissolve his father\'s company. In return, Saito promises to use his influence to clear Cobb of a murder charge, allowing Cobb to return home to his children. Cobb accepts the offer and assembles his team: Eames, a conman and identity forger; Yusuf, a chemist who concocts a powerful sedative for a stable "dream within a dream" strategy; and Ariadne, an architecture student tasked with designing the labyrinth of the dream landscapes, recruited with the help of Cobb\'s father-in-law, Professor Stephen Miles. While dream-sharing with Cobb, Ariadne learns his subconscious houses an invasive projection of his late wife Mal. When the elder Fischer dies in Sydney, Robert Fischer accompanies the body on a ten-hour flight back to ',
   'The plot is non-linear, and the end scene of the film shows the real beginning of the story.[7] There are two main roles, one that is played out in the dream, and the other one in reality, called respectively Nikhil and Nikki.[7] The plot starts with the protagonist being in a state of coma and continuing only on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white.[8] Sanjay, a detective from the Mumbai police Crime Branch starts investigating the incident that caused the protagonist\'s (Sathish Ninasam) current state. While Sanjay is going through the protagonist\'s belongings he stumbles upon some scribbled notes and a mysterious pill. Meanwhile, the police capture two suspects and interrogate them. The story starts with Nikki in a village near Mandya, working as an usher/"torch-shiner" in a Bengaluru movie theatre owned by Shankranna (Achyuth Kumar). Nikki has insomnia and yearns for a companion. On one of his sleepless nights Nikki is contacted by a drug dealer who gives him Lucia pills as a solution to his sleeping problems. This drug is said to have the capacity to help one dream the ',
   'The plot is non-linear, and the end scene of the film shows the real beginning of the story.[7] There are two main roles, one that is played out in the dream, and the other one in reality, called respectively Nikhil and Nikki.[7] The plot starts with the protagonist being in a state of coma and continuing only on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white.[8] Sanjay, a detective from the Mumbai police Crime Branch starts investigating the incident that caused the protagonist\'s (Sathish Ninasam) current state. While Sanjay is going through the protagonist\'s belongings he stumbles upon some scribbled notes and a mysterious pill. Meanwhile, the police capture two suspects and interrogate them. The story starts with Nikki in a village near Mandya, working as an usher/"torch-shiner" in a Bengaluru movie theatre owned by Shankranna (Achyuth Kumar). Nikki has insomnia and yearns for a companion. On one of his sleepless nights Nikki is contacted by a drug dealer who gives him Lucia pills as a solution to his sleeping problems. This drug is said to have the capacity to help one dream the ',
   'The film starts with a man, Ryjkin, trying to escape from the Cube. He enters a room and is sprayed with liquid that he thinks is only water. However, when he rubs the back of his hand due to itchiness, his flesh liquifies and falls off. This soon happens all over his body, as he then melts on the floor and dies as a result. A man named Eric is watching a video feed of this in an observation room with a co-worker named Dodd. Afterwards, Eric is shown to be sketching a portrait of Dodd in the form of a superhero called Chessman, while playing chess with him at the same time. Dodd has the chess board in front of him, but Eric is at another table, simply drawing and naming his moves. Eric seems to be vastly intelligent, calculating all of Dodd\'s moves. After Eric wins, he asks Dodd questions about their missing colleagues. Dodd tells him not to ask too many questions or get involved with the occupants of the Cube because it wouldn\'t make "those upstairs" happy. Both Eric and Dodd get an order from "upstairs" that asks them to record the dream of a subject, ',
   'The movie follows a man\'s search for perfection in a world where life rarely measures up to the idealized images that constantly bombard us. Gary Shaller (Freeman), who gained commercial success in previous years as the keyboard player in the fictional band "On The One". He is in a failing marriage with Dora (Gwyneth Paltrow), and working for his former band mate Paul (Simon Pegg), writing and recording commercial jingles. Gary eventually discovers that he is having lucid dreams about a glamorous woman named Anna (Penélope Cruz), with whom he is deeply infatuated. He aims to learn more about lucid dreaming by buying books and even attending classes taught by an eccentric lucid-dreaming enthusiast, Mel (Danny DeVito). Gary eventually discovers that the girl he dreams about does, in fact, exist. Paul arranges for Gary to meet her, but this proves disappointing, as she fails to live up to the expectations that Gary has built up in his dreams of her. He eventually continues to dream about her, and even soundproofs his apartment, and makes other efforts to be able to sleep longer, so that he can remain with Anna for longer periods of time. Eventually, feeling as though he is ',
   'Eleven-year-old Jake Chambers experiences visions involving a Man in Black who seeks to destroy a Tower and bring ruin to the Universe, and a Gunslinger who opposes him. Jake\'s mother, stepfather, and psychiatrists dismiss these as dreams resulting from the trauma of his father’s death the previous year. At his apartment home in New York City, a group of workers from an alleged psychiatric facility offer to rehabilitate Jake; recognizing them from his visions as monsters wearing human skin, he flees. Jake tracks down an abandoned house from one of his visions, discovers a high-tech portal, and travels to a post-apocalyptic world called Mid-World. In Mid-World, Jake encounters the last Gunslinger, Roland Deschain who emerged in his visions. Roland is pursuing Walter Padick, the Man in Black, who had also appeared in Jake’s dreams, across a desert, seeking to kill him in revenge for the murder of his father, Steven, and all remaining gunslingers. He explains that Walter, over the decades, has been abducting psychic children, and is attempting to use their "shine" to bring down the Dark Tower, a fabled structure located at the center of the Universe; this will allow beings from the darkness outside to invade and ',
   "Author Roger Cobb is a troubled man, having been separated from his wife; their only son Jimmy disappeared without a trace and his aunt committed suicide by hanging. On top of everything else, he has been pressured by his publisher to write another book. To the chagrin of his fans and publisher, Cobb plans a novel based on his experiences in Vietnam, instead of another horror story, as a way to purge himself of the horrors that he had experienced while there. After his aunt's funeral, Cobb decides to live inside her house to write instead of selling it, as recommended by the estate attorney. After moving in, Cobb begins to have powerful graphic nightmares, including thoughts about his comrade, Big Ben, who died in Vietnam. In addition, strange phenomena spring forth from the house, haunting him in his waking hours. He tries communicating his fears to his next door neighbor Harold, but he thinks that Cobb is crazy. One night while investigating a noise coming from his late aunt's bedroom, Cobb is attacked by a deformed monster inside the closet. Soon, more attacks occur: levitating garden tools attack him, his wife appears and transforms into a hideous hag-like creature ",
   'In 2014, 17-year-old high school senior and aspiring inventor David Raskin (Jonny Weston) is admitted into MIT, but is unable to afford its tuition fees. Upon learning his mother, Kathy Raskin (Amy Landecker), is planning to sell the house to help pay for his college, David enlists his sister Christina (Virginia Gardner) and his friends Adam Le (Allen Evangelista) and Quinn Goldberg (Sam Lerner) to sift through the belongings of his father Ben Raskin (Gary Weeks), an inventor who died in a car crash on David\'s seventh birthday, in the hope of finding something that David can use to get a scholarship instead. David finds an old camera with a video recording of his seventh birthday party, in which he briefly spots his 17-year-old self in a reflection. Noticing how he appears to be reaching for a basement light switch in the reflection, David and his friends go to the basement, which was forbidden by his father. Underneath a trapdoor activated by the basement switch, the group find the blueprints of a temporal relocation device that Ben was developing named "Project Almanac", and use the available resources to build a functional time machine. David, Christina, Adam, and Quinn later use ',
   'The plot is non-linear, starting by showing the final scene of the film. The plot starts with the protagonist being in a state of coma and living on life support. The film, from the beginning, tells two stories of the same person, one in colour and the other in black and white. A detective from Mumbai crime branch starts investigating the incident that caused the protagonist\'s (Siddharth) current state. The Detective going through his belongings stumbles upon some scribbled notes and a mysterious pill. Meanwhile, police capture two suspects and interrogate them for information. The story starts with Vicky who is from a village and working as an Usher/"torch-shiner" in a movie theatre owned by Durai (Aadukalam Naren). Vicky suffers from insomnia. On one of his sleepless nights Vicky is contacted by a drug dealer who gives him Lucia pills as a solution to his sleeping problems. This drug is said to have the capability to help one dream the life they want but has the side-effect, that on discontinuation the same dreams shall turn into a nightmare. With the help of the Lucia pills, Vicky starts seeing himself as being a successful actor called Vignesh surrounded by people he ',
   'The film starts with a young woman named Becky (Greer Kent), shown to be trapped in the Cube. She enters another room, but unknown to her, the room has reversed gravity, as she is pulled up, and it is implied that she is killed. Some time later, a woman named Kate (Kari Matchett), detective Simon (Geraint Wyn Davies), a blind girl named Sasha (Grace Lynn Kung), engineer Jerry (Neil Crone), game developer Max (Matthew Ferguson), lawyer Julia (Lindsey Connell), and an elderly woman named Mrs. Paley (Barbara Gordon) find themselves trapped in brightly lit cubes, each with a panel on each of the six sides, which are doors to other rooms. They come across Colonel Thomas Maguire (Bruce Gray), who says that they have to solve the code in order to leave the mysterious place. Just as he finishes, a wall begins to close in on the group. The group escapes while Thomas stays behind, while Kate and Simon watch in horror as Thomas is disintegrated by the wall. Later experiences around the cube reveal that gravity can operate in different directions in each room, while Mrs. Paley, who is revealed to be a retired theoretical mathematician, and Jerry, realize ']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'short_plot': 'Dominick "Dom" Cobb and Arthur are "extractors", who perform corporate espionage using an experimental military technology to infiltrate the subconscious of their targets and extract valuable information through a shared dream world. Their latest target, Japanese businessman Saito, reveals that he arranged their mission himself to test Cobb for a seemingly impossible job: planting an idea in a person\'s subconscious, or "inception". To break up the energy conglomerate of ailing competitor Maurice Fischer, Saito wants Cobb to convince Fischer\'s son and heir, Robert, to dissolve his father\'s company. In return, Saito promises to use his influence to clear Cobb of a murder charge, allowing Cobb to return home to his children. Cobb accepts the offer and assembles his team: Eames, a conman and identity forger; Yusuf, a chemist who concocts a powerful sedative for a stable "dream within a dream" strategy; and Ariadne, an architecture student tasked with designing the labyrinth of the dream landscapes, recruited with the help of Cobb\'s father-in-law, Professor Stephen Miles. While dream-sharing with Cobb, Ariadne learns his subconscious houses an invasive projection of his late wife Mal. When the elder Fischer dies in Sydney, Robert Fischer accompanies the body on a ten-hour flight back to',
    'Title': 'Inception',
    'Plot': 'Dominick "Dom" Cobb and Arthur are "extractors", who perform corporate espionage using an experimental military technology to infiltrate the subconscious of their targets and extract valuable information through a shared dream world. Their latest target, Japanese businessman Saito, reveals that he arranged their mission himself to test Cobb for a seemingly impossible job: planting an idea in a person\'s subconscious, or "inception". To break up the energy conglomerate of ailing competitor Maurice Fischer, Saito wants Cobb to convince Fischer\'s son and heir, Robert, to dissolve his father\'s company. In return, Saito promises to use his influence to clear Cobb of a murder charge, allowing Cobb to return home to his children. Cobb accepts the offer and assembles his team: Eames, a conman and identity forger; Yusuf, a chemist who concocts a powerful sedative for a stable "dream within a dream" strategy; and Ariadne, an architecture student tasked with designing the labyrinth of the dream landscapes, recruited with the help of Cobb\'s father-in-law, Professor Stephen Miles. While dream-sharing with Cobb, Ariadne learns his subconscious houses an invasive projection of his late wife Mal.\r\nWhen the elder Fischer dies in Sydney, Robert Fischer accompanies the body on a ten-hour flight back to Los Angeles, which the team (including Saito, who wants to verify their success) uses as an opportunity to sedate and take Fischer into a shared dream. At each dream level, the person generating the dream stays behind to set up a "kick" that will be used to awaken the other sleeping team members from the deeper dream level; to be successful, these kicks must occur simultaneously at each dream level, a fact complicated due to the nature of time which flows much faster in each successive level. The first level is Yusuf\'s dream of a rainy Los Angeles. The team abducts Fischer, but they are attacked by armed projections from Fischer\'s subconscious, which has been specifically trained to defend him against such intruders. The team takes Fischer and a wounded Saito to a warehouse, where Cobb reveals that while dying in the dream would normally wake Saito up, the powerful sedatives needed to stabilize the multi-level dream will instead send a dying dreamer into "limbo", a world of infinite subconscious from which escape is extremely difficult, if not impossible, and a dreamer risks forgetting they are in a dream. Despite these setbacks, the team continues with the mission.\r\nEames impersonates Fischer\'s godfather, Peter Browning, to suggest Fischer reconsider his father\'s will. Yusuf drives the van as the other dreamers are sedated into the second level. In the second level, a hotel dreamed by Arthur, Cobb persuades Fischer that he has been kidnapped by Browning and Cobb is his subconscious protector. Cobb persuades him to go down another level to explore Browning\'s subconscious (in reality, it is a ruse to enter Fischer\'s). The third level is a fortified hospital on a snowy mountain dreamed by Eames. The team has to infiltrate it and hold off the guards as Cobb takes Fischer into the equivalent of his subconscious. Yusuf, under pursuit by Fischer\'s projections in the first level, deliberately drives off a bridge and initiates his kick too soon. This causes an avalanche in Eames\' level and removes the gravity of Arthur\'s level, forcing him to improvise a new kick synchronized with the van hitting the water. Mal\'s projection emerges and kills Fischer; Cobb kills Mal, and Saito succumbs to his wounds. Cobb and Ariadne enter Limbo to rescue Fischer and Saito, while Eames sets up a kick by rigging the hospital with explosives.\r\nCobb reveals to Ariadne that he and Mal went to Limbo while experimenting with the dream-sharing technology. Sedated for a few hours of real time, they spent fifty years in a dream constructing a world from their shared memories. When Mal refused to return to reality, Cobb used a rudimentary form of inception by reactivating her totem (an object dreamers use to distinguish dreams from reality) and reminding her subconscious that their world was not real. However, when she woke up, Mal still believed that she was dreaming. In an attempt to "wake up" for real, Mal committed suicide and framed Cobb for her death to force him to do the same. Facing a murder charge, Cobb fled the U.S., leaving his children in the care of Professor Miles.\r\nThrough his confession, Cobb makes peace with his guilt over Mal\'s death. Ariadne kills Mal\'s projection and wakes Fischer up with a kick. Revived at the mountain fort, Fischer enters a safe room to discover and accept the planted idea: a projection of his dying father telling him to be his own man. While Cobb remains in Limbo to search for Saito, the other team members ride the synchronized kicks back to reality. Cobb eventually finds an aged Saito in Limbo and reminds him of their agreement. The dreamers all awake on the plane and Saito makes a phone call.\r\nUpon arrival at Los Angeles Airport, Cobb passes the U.S. immigration checkpoint and Professor Miles accompanies him to his home. Using his totem—a spinning top that spins indefinitely in a dream world but falls over in reality—Cobb conducts a test to prove that he is indeed in the real world, but he ignores its result and instead joins his children in the garden.',
    'Release_Year': 2010},
   {'Release_Year': 1998,
    'Title': 'Lucia',

In [ ]:
cache_results = cache_collection.query(
    query_texts = [query],
    n_results = 2
)

In [ ]:
# Implementing Cache in Semantic Search

# Set a threshold for cache search
threshold = 0.2

ids = []
documents = []
distances = []
metadatas = []
results_df = pd.DataFrame()

# Check if the distance is greater than the threshold, if so, return results from the main collection
if cache_results['distances'][0] == [] or cache_results['distances'][0][0] > threshold:
    # Query the collection against the user query and return the results
    results = collection.query(
        query_texts=query,
        n_results=5
    )

    # Store the query in cache_collection as a document with respect to ChromaDB for future reference
    # Store retrieved text, ids, distances, and metadatas in cache_collection as metadatas, so they can be fetched easily if a query indeed matches to a query in cache
    Keys = []
    Values = []

    for key, val in results.items():
        if val is None:
            continue
        for i in range(len(val[0])):  # Iterate over the actual length of val
            Keys.append(str(key) + str(i))
            if len(val[0]) > i:  # Check if the current index exists in val
                Values.append(str(val[0][i]))

    cache_collection.add(
        documents=[query],
        ids=[query],
        metadatas=dict(zip(Keys, Values))
    )

    # Print message indicating the results are found in the main collection
    print("Not found in cache. Found in the main collection.")

    # Construct a DataFrame from the query results
    result_dict = {'Metadatas': results['metadatas'][0], 'Documents': results['documents'][0], 'Distances': results['distances'][0], "IDs": results["ids"][0]}
    results_df = pd.DataFrame.from_dict(result_dict)


# If the distance is less than the threshold, return results from the cache
elif cache_results['distances'][0][0] <= threshold and cache_results['ids']:
    cache_result_dict = cache_results['metadatas'][0][0]

    # Loop through each inner list and then through the dictionary
    for key, value in cache_result_dict.items():
        if 'ids' in key:
            ids.append(value)
        elif 'documents' in key:
            documents.append(value)
        elif 'distances' in key:
            distances.append(value)
        elif 'metadatas' in key:
            metadatas.append(value)

    # Print message indicating the results are found in the cache
    print("Found in cache!")

    # Create a DataFrame from the cached results
    results_df = pd.DataFrame({
        'IDs': ids,
        'Documents': documents,
        'Distances': distances,
        'Metadatas': metadatas
    })
else:
    # Print message indicating no valid results found in cache
    print("No valid results found in cache!")

Not found in cache. Found in the main collection.

In [ ]:
results_df.head()

,Metadatas,Documents,Distances,IDs
0,"{'Release_Year': 2010, 'short_plot': 'Dominick...","Dominick ""Dom"" Cobb and Arthur are ""extractors...",0.401830,10570
1,"{'Release_Year': 1998, 'Title': 'Lucia', 'Plot...","The plot is non-linear, and the end scene of t...",0.885444,14486
2,"{'Plot': 'The plot is non-linear, and the end ...","The plot is non-linear, and the end scene of t...",0.885444,21094
3,"{'short_plot': 'The film starts with a man, Ry...","The film starts with a man, Ryjkin, trying to ...",0.905679,15871
4,"{'Release_Year': 2007, 'Title': 'The Good Nigh...",The movie follows a man's search for perfectio...,0.986720,9932

In [ ]:
from sentence_transformers import CrossEncoder, util

In [ ]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [ ]:
### Generating cross_encoder scores query

cross_inputs = [[query, response] for response in results_df['Documents']]
cross_rerank_scores = cross_encoder.predict(cross_inputs)

results_df['Reranked_scores'] = cross_rerank_scores

In [ ]:

semantic = results_df.sort_values(by='Distances')
semantic[:3]

,Metadatas,Documents,Distances,IDs,Reranked_scores
0,"{'Release_Year': 2010, 'short_plot': 'Dominick...","Dominick ""Dom"" Cobb and Arthur are ""extractors...",0.401830,10570,3.257682
1,"{'Release_Year': 1998, 'Title': 'Lucia', 'Plot...","The plot is non-linear, and the end scene of t...",0.885444,14486,-7.524955
2,"{'Plot': 'The plot is non-linear, and the end ...","The plot is non-linear, and the end scene of t...",0.885444,21094,-7.524955

In [ ]:
## Rank based

rank = results_df.sort_values(by='Reranked_scores')
rank[:3]

,Metadatas,Documents,Distances,IDs,Reranked_scores
4,"{'Release_Year': 2007, 'Title': 'The Good Nigh...",The movie follows a man's search for perfectio...,0.986720,9932,-7.952139
1,"{'Release_Year': 1998, 'Title': 'Lucia', 'Plot...","The plot is non-linear, and the end scene of t...",0.885444,14486,-7.524955
2,"{'Plot': 'The plot is non-linear, and the end ...","The plot is non-linear, and the end scene of t...",0.885444,21094,-7.524955

In [ ]:
final = rank[["Documents", "Metadatas", "IDs"]]

In [ ]:
final

,Documents,Metadatas,IDs
4,The movie follows a man's search for perfectio...,"{'Release_Year': 2007, 'Title': 'The Good Nigh...",9932
1,"The plot is non-linear, and the end scene of t...","{'Release_Year': 1998, 'Title': 'Lucia', 'Plot...",14486
2,"The plot is non-linear, and the end scene of t...","{'Plot': 'The plot is non-linear, and the end ...",21094
3,"The film starts with a man, Ryjkin, trying to ...","{'short_plot': 'The film starts with a man, Ry...",15871
0,"Dominick ""Dom"" Cobb and Arthur are ""extractors...","{'Release_Year': 2010, 'short_plot': 'Dominick...",10570